// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: identity.proto

package identityservice

import (
	"context"

	"github.com/menli02/QR-menu/proto/identity/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateStaffRequest       = v1_identitypb.CreateStaffRequest
	DeleteStaffRequest       = v1_identitypb.DeleteStaffRequest
	DeleteStaffResponse      = v1_identitypb.DeleteStaffResponse
	GetStaffRequest          = v1_identitypb.GetStaffRequest
	IssueGuestTokenRequest   = v1_identitypb.IssueGuestTokenRequest
	JWKS                     = v1_identitypb.JWKS
	ListJWKSRequest          = v1_identitypb.ListJWKSRequest
	ListStaffRequest         = v1_identitypb.ListStaffRequest
	ListStaffResponse        = v1_identitypb.ListStaffResponse
	LoginRequest             = v1_identitypb.LoginRequest
	RefreshRequest           = v1_identitypb.RefreshRequest
	RevokeRequest            = v1_identitypb.RevokeRequest
	RevokeResponse           = v1_identitypb.RevokeResponse
	SetStaffPasswordRequest  = v1_identitypb.SetStaffPasswordRequest
	SetStaffPasswordResponse = v1_identitypb.SetStaffPasswordResponse
	Staff                    = v1_identitypb.Staff
	TokenPair                = v1_identitypb.TokenPair
	UpdateStaffRequest       = v1_identitypb.UpdateStaffRequest

	IdentityService interface {
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*TokenPair, error)
		Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*TokenPair, error)
		Revoke(ctx context.Context, in *RevokeRequest, opts ...grpc.CallOption) (*RevokeResponse, error)
		GetStaff(ctx context.Context, in *GetStaffRequest, opts ...grpc.CallOption) (*Staff, error)
		// IssueGuestToken mints an anonymous guest JWT bound to
		IssueGuestToken(ctx context.Context, in *IssueGuestTokenRequest, opts ...grpc.CallOption) (*TokenPair, error)
		// ListJWKS exposes the public signing keys so gateway instances can
		ListJWKS(ctx context.Context, in *ListJWKSRequest, opts ...grpc.CallOption) (*JWKS, error)
		ListStaff(ctx context.Context, in *ListStaffRequest, opts ...grpc.CallOption) (*ListStaffResponse, error)
		CreateStaff(ctx context.Context, in *CreateStaffRequest, opts ...grpc.CallOption) (*Staff, error)
		UpdateStaff(ctx context.Context, in *UpdateStaffRequest, opts ...grpc.CallOption) (*Staff, error)
		DeleteStaff(ctx context.Context, in *DeleteStaffRequest, opts ...grpc.CallOption) (*DeleteStaffResponse, error)
		SetStaffPassword(ctx context.Context, in *SetStaffPasswordRequest, opts ...grpc.CallOption) (*SetStaffPasswordResponse, error)
	}

	defaultIdentityService struct {
		cli zrpc.Client
	}
)

func NewIdentityService(cli zrpc.Client) IdentityService {
	return &defaultIdentityService{
		cli: cli,
	}
}

func (m *defaultIdentityService) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*TokenPair, error) {
	client := v1_identitypb.NewIdentityServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultIdentityService) Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*TokenPair, error) {
	client := v1_identitypb.NewIdentityServiceClient(m.cli.Conn())
	return client.Refresh(ctx, in, opts...)
}

func (m *defaultIdentityService) Revoke(ctx context.Context, in *RevokeRequest, opts ...grpc.CallOption) (*RevokeResponse, error) {
	client := v1_identitypb.NewIdentityServiceClient(m.cli.Conn())
	return client.Revoke(ctx, in, opts...)
}

func (m *defaultIdentityService) GetStaff(ctx context.Context, in *GetStaffRequest, opts ...grpc.CallOption) (*Staff, error) {
	client := v1_identitypb.NewIdentityServiceClient(m.cli.Conn())
	return client.GetStaff(ctx, in, opts...)
}

// IssueGuestToken mints an anonymous guest JWT bound to
func (m *defaultIdentityService) IssueGuestToken(ctx context.Context, in *IssueGuestTokenRequest, opts ...grpc.CallOption) (*TokenPair, error) {
	client := v1_identitypb.NewIdentityServiceClient(m.cli.Conn())
	return client.IssueGuestToken(ctx, in, opts...)
}

// ListJWKS exposes the public signing keys so gateway instances can
func (m *defaultIdentityService) ListJWKS(ctx context.Context, in *ListJWKSRequest, opts ...grpc.CallOption) (*JWKS, error) {
	client := v1_identitypb.NewIdentityServiceClient(m.cli.Conn())
	return client.ListJWKS(ctx, in, opts...)
}

func (m *defaultIdentityService) ListStaff(ctx context.Context, in *ListStaffRequest, opts ...grpc.CallOption) (*ListStaffResponse, error) {
	client := v1_identitypb.NewIdentityServiceClient(m.cli.Conn())
	return client.ListStaff(ctx, in, opts...)
}

func (m *defaultIdentityService) CreateStaff(ctx context.Context, in *CreateStaffRequest, opts ...grpc.CallOption) (*Staff, error) {
	client := v1_identitypb.NewIdentityServiceClient(m.cli.Conn())
	return client.CreateStaff(ctx, in, opts...)
}

func (m *defaultIdentityService) UpdateStaff(ctx context.Context, in *UpdateStaffRequest, opts ...grpc.CallOption) (*Staff, error) {
	client := v1_identitypb.NewIdentityServiceClient(m.cli.Conn())
	return client.UpdateStaff(ctx, in, opts...)
}

func (m *defaultIdentityService) DeleteStaff(ctx context.Context, in *DeleteStaffRequest, opts ...grpc.CallOption) (*DeleteStaffResponse, error) {
	client := v1_identitypb.NewIdentityServiceClient(m.cli.Conn())
	return client.DeleteStaff(ctx, in, opts...)
}

func (m *defaultIdentityService) SetStaffPassword(ctx context.Context, in *SetStaffPasswordRequest, opts ...grpc.CallOption) (*SetStaffPasswordResponse, error) {
	client := v1_identitypb.NewIdentityServiceClient(m.cli.Conn())
	return client.SetStaffPassword(ctx, in, opts...)
}
