// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: order.proto

package server

import (
	"context"

	"github.com/menli02/QR-menu/proto/order/v1"
	"github.com/menli02/QR-menu/services/order/internal/logic/orderservice"
	"github.com/menli02/QR-menu/services/order/internal/svc"
)

type OrderServiceServer struct {
	svcCtx *svc.ServiceContext
	v1_orderpb.UnimplementedOrderServiceServer
}

func NewOrderServiceServer(svcCtx *svc.ServiceContext) *OrderServiceServer {
	return &OrderServiceServer{
		svcCtx: svcCtx,
	}
}

// CreateOrder is idempotent on idempotency_key (scoped to venue_id).
func (s *OrderServiceServer) CreateOrder(ctx context.Context, in *v1_orderpb.CreateOrderRequest) (*v1_orderpb.Order, error) {
	l := orderservicelogic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}

func (s *OrderServiceServer) ListOrders(ctx context.Context, in *v1_orderpb.ListOrdersRequest) (*v1_orderpb.ListOrdersResponse, error) {
	l := orderservicelogic.NewListOrdersLogic(ctx, s.svcCtx)
	return l.ListOrders(in)
}

func (s *OrderServiceServer) GetBill(ctx context.Context, in *v1_orderpb.GetBillRequest) (*v1_orderpb.Bill, error) {
	l := orderservicelogic.NewGetBillLogic(ctx, s.svcCtx)
	return l.GetBill(in)
}

func (s *OrderServiceServer) CreateServiceRequest(ctx context.Context, in *v1_orderpb.CreateServiceRequestRequest) (*v1_orderpb.ServiceRequest, error) {
	l := orderservicelogic.NewCreateServiceRequestLogic(ctx, s.svcCtx)
	return l.CreateServiceRequest(in)
}

func (s *OrderServiceServer) TransitionOrder(ctx context.Context, in *v1_orderpb.TransitionOrderRequest) (*v1_orderpb.Order, error) {
	l := orderservicelogic.NewTransitionOrderLogic(ctx, s.svcCtx)
	return l.TransitionOrder(in)
}

func (s *OrderServiceServer) TransitionOrderItem(ctx context.Context, in *v1_orderpb.TransitionOrderItemRequest) (*v1_orderpb.Order, error) {
	l := orderservicelogic.NewTransitionOrderItemLogic(ctx, s.svcCtx)
	return l.TransitionOrderItem(in)
}

func (s *OrderServiceServer) ListTickets(ctx context.Context, in *v1_orderpb.ListTicketsRequest) (*v1_orderpb.ListTicketsResponse, error) {
	l := orderservicelogic.NewListTicketsLogic(ctx, s.svcCtx)
	return l.ListTickets(in)
}

func (s *OrderServiceServer) GetTableSession(ctx context.Context, in *v1_orderpb.GetTableSessionRequest) (*v1_orderpb.TableSession, error) {
	l := orderservicelogic.NewGetTableSessionLogic(ctx, s.svcCtx)
	return l.GetTableSession(in)
}

func (s *OrderServiceServer) ListActiveTableSessions(ctx context.Context, in *v1_orderpb.ListActiveTableSessionsRequest) (*v1_orderpb.ListActiveTableSessionsResponse, error) {
	l := orderservicelogic.NewListActiveTableSessionsLogic(ctx, s.svcCtx)
	return l.ListActiveTableSessions(in)
}

func (s *OrderServiceServer) CloseTableSession(ctx context.Context, in *v1_orderpb.CloseTableSessionRequest) (*v1_orderpb.TableSession, error) {
	l := orderservicelogic.NewCloseTableSessionLogic(ctx, s.svcCtx)
	return l.CloseTableSession(in)
}

func (s *OrderServiceServer) ListServiceRequests(ctx context.Context, in *v1_orderpb.ListServiceRequestsRequest) (*v1_orderpb.ListServiceRequestsResponse, error) {
	l := orderservicelogic.NewListServiceRequestsLogic(ctx, s.svcCtx)
	return l.ListServiceRequests(in)
}

func (s *OrderServiceServer) TransitionServiceRequest(ctx context.Context, in *v1_orderpb.TransitionServiceRequestRequest) (*v1_orderpb.ServiceRequest, error) {
	l := orderservicelogic.NewTransitionServiceRequestLogic(ctx, s.svcCtx)
	return l.TransitionServiceRequest(in)
}

func (s *OrderServiceServer) GetDayReport(ctx context.Context, in *v1_orderpb.GetDayReportRequest) (*v1_orderpb.DayReport, error) {
	l := orderservicelogic.NewGetDayReportLogic(ctx, s.svcCtx)
	return l.GetDayReport(in)
}
