// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.2
// source: order.proto

// OrderService owns TableSession, GuestSession, Order, OrderItem,
// ServiceRequest and Bill. The transactional core; correctness-critical,
// isolated failure domain. See docs/TZ.md §6, §7.1, §7.2.

package v1_orderpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderService_CreateOrder_FullMethodName              = "/order.v1.OrderService/CreateOrder"
	OrderService_ListOrders_FullMethodName               = "/order.v1.OrderService/ListOrders"
	OrderService_GetBill_FullMethodName                  = "/order.v1.OrderService/GetBill"
	OrderService_CreateServiceRequest_FullMethodName     = "/order.v1.OrderService/CreateServiceRequest"
	OrderService_TransitionOrder_FullMethodName          = "/order.v1.OrderService/TransitionOrder"
	OrderService_TransitionOrderItem_FullMethodName      = "/order.v1.OrderService/TransitionOrderItem"
	OrderService_ListTickets_FullMethodName              = "/order.v1.OrderService/ListTickets"
	OrderService_GetTableSession_FullMethodName          = "/order.v1.OrderService/GetTableSession"
	OrderService_ListActiveTableSessions_FullMethodName  = "/order.v1.OrderService/ListActiveTableSessions"
	OrderService_CloseTableSession_FullMethodName        = "/order.v1.OrderService/CloseTableSession"
	OrderService_ListServiceRequests_FullMethodName      = "/order.v1.OrderService/ListServiceRequests"
	OrderService_TransitionServiceRequest_FullMethodName = "/order.v1.OrderService/TransitionServiceRequest"
	OrderService_GetDayReport_FullMethodName             = "/order.v1.OrderService/GetDayReport"
)

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderServiceClient interface {
	// CreateOrder is idempotent on idempotency_key (scoped to venue_id).
	// Internally the order service calls catalog.ResolveOrderItems to price
	// and validate availability before committing (docs/TZ.md §7.2).
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*Order, error)
	ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (*ListOrdersResponse, error)
	GetBill(ctx context.Context, in *GetBillRequest, opts ...grpc.CallOption) (*Bill, error)
	CreateServiceRequest(ctx context.Context, in *CreateServiceRequestRequest, opts ...grpc.CallOption) (*ServiceRequest, error)
	TransitionOrder(ctx context.Context, in *TransitionOrderRequest, opts ...grpc.CallOption) (*Order, error)
	TransitionOrderItem(ctx context.Context, in *TransitionOrderItemRequest, opts ...grpc.CallOption) (*Order, error)
	ListTickets(ctx context.Context, in *ListTicketsRequest, opts ...grpc.CallOption) (*ListTicketsResponse, error)
	GetTableSession(ctx context.Context, in *GetTableSessionRequest, opts ...grpc.CallOption) (*TableSession, error)
	ListActiveTableSessions(ctx context.Context, in *ListActiveTableSessionsRequest, opts ...grpc.CallOption) (*ListActiveTableSessionsResponse, error)
	CloseTableSession(ctx context.Context, in *CloseTableSessionRequest, opts ...grpc.CallOption) (*TableSession, error)
	ListServiceRequests(ctx context.Context, in *ListServiceRequestsRequest, opts ...grpc.CallOption) (*ListServiceRequestsResponse, error)
	TransitionServiceRequest(ctx context.Context, in *TransitionServiceRequestRequest, opts ...grpc.CallOption) (*ServiceRequest, error)
	GetDayReport(ctx context.Context, in *GetDayReportRequest, opts ...grpc.CallOption) (*DayReport, error)
}

type orderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceClient(cc grpc.ClientConnInterface) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*Order, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Order)
	err := c.cc.Invoke(ctx, OrderService_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (*ListOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOrdersResponse)
	err := c.cc.Invoke(ctx, OrderService_ListOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetBill(ctx context.Context, in *GetBillRequest, opts ...grpc.CallOption) (*Bill, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Bill)
	err := c.cc.Invoke(ctx, OrderService_GetBill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) CreateServiceRequest(ctx context.Context, in *CreateServiceRequestRequest, opts ...grpc.CallOption) (*ServiceRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceRequest)
	err := c.cc.Invoke(ctx, OrderService_CreateServiceRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) TransitionOrder(ctx context.Context, in *TransitionOrderRequest, opts ...grpc.CallOption) (*Order, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Order)
	err := c.cc.Invoke(ctx, OrderService_TransitionOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) TransitionOrderItem(ctx context.Context, in *TransitionOrderItemRequest, opts ...grpc.CallOption) (*Order, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Order)
	err := c.cc.Invoke(ctx, OrderService_TransitionOrderItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) ListTickets(ctx context.Context, in *ListTicketsRequest, opts ...grpc.CallOption) (*ListTicketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTicketsResponse)
	err := c.cc.Invoke(ctx, OrderService_ListTickets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetTableSession(ctx context.Context, in *GetTableSessionRequest, opts ...grpc.CallOption) (*TableSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TableSession)
	err := c.cc.Invoke(ctx, OrderService_GetTableSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) ListActiveTableSessions(ctx context.Context, in *ListActiveTableSessionsRequest, opts ...grpc.CallOption) (*ListActiveTableSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActiveTableSessionsResponse)
	err := c.cc.Invoke(ctx, OrderService_ListActiveTableSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) CloseTableSession(ctx context.Context, in *CloseTableSessionRequest, opts ...grpc.CallOption) (*TableSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TableSession)
	err := c.cc.Invoke(ctx, OrderService_CloseTableSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) ListServiceRequests(ctx context.Context, in *ListServiceRequestsRequest, opts ...grpc.CallOption) (*ListServiceRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServiceRequestsResponse)
	err := c.cc.Invoke(ctx, OrderService_ListServiceRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) TransitionServiceRequest(ctx context.Context, in *TransitionServiceRequestRequest, opts ...grpc.CallOption) (*ServiceRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceRequest)
	err := c.cc.Invoke(ctx, OrderService_TransitionServiceRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetDayReport(ctx context.Context, in *GetDayReportRequest, opts ...grpc.CallOption) (*DayReport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DayReport)
	err := c.cc.Invoke(ctx, OrderService_GetDayReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
// All implementations must embed UnimplementedOrderServiceServer
// for forward compatibility.
type OrderServiceServer interface {
	// CreateOrder is idempotent on idempotency_key (scoped to venue_id).
	// Internally the order service calls catalog.ResolveOrderItems to price
	// and validate availability before committing (docs/TZ.md §7.2).
	CreateOrder(context.Context, *CreateOrderRequest) (*Order, error)
	ListOrders(context.Context, *ListOrdersRequest) (*ListOrdersResponse, error)
	GetBill(context.Context, *GetBillRequest) (*Bill, error)
	CreateServiceRequest(context.Context, *CreateServiceRequestRequest) (*ServiceRequest, error)
	TransitionOrder(context.Context, *TransitionOrderRequest) (*Order, error)
	TransitionOrderItem(context.Context, *TransitionOrderItemRequest) (*Order, error)
	ListTickets(context.Context, *ListTicketsRequest) (*ListTicketsResponse, error)
	GetTableSession(context.Context, *GetTableSessionRequest) (*TableSession, error)
	ListActiveTableSessions(context.Context, *ListActiveTableSessionsRequest) (*ListActiveTableSessionsResponse, error)
	CloseTableSession(context.Context, *CloseTableSessionRequest) (*TableSession, error)
	ListServiceRequests(context.Context, *ListServiceRequestsRequest) (*ListServiceRequestsResponse, error)
	TransitionServiceRequest(context.Context, *TransitionServiceRequestRequest) (*ServiceRequest, error)
	GetDayReport(context.Context, *GetDayReportRequest) (*DayReport, error)
	mustEmbedUnimplementedOrderServiceServer()
}

// UnimplementedOrderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderServiceServer struct{}

func (UnimplementedOrderServiceServer) CreateOrder(context.Context, *CreateOrderRequest) (*Order, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedOrderServiceServer) ListOrders(context.Context, *ListOrdersRequest) (*ListOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOrders not implemented")
}
func (UnimplementedOrderServiceServer) GetBill(context.Context, *GetBillRequest) (*Bill, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBill not implemented")
}
func (UnimplementedOrderServiceServer) CreateServiceRequest(context.Context, *CreateServiceRequestRequest) (*ServiceRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateServiceRequest not implemented")
}
func (UnimplementedOrderServiceServer) TransitionOrder(context.Context, *TransitionOrderRequest) (*Order, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransitionOrder not implemented")
}
func (UnimplementedOrderServiceServer) TransitionOrderItem(context.Context, *TransitionOrderItemRequest) (*Order, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransitionOrderItem not implemented")
}
func (UnimplementedOrderServiceServer) ListTickets(context.Context, *ListTicketsRequest) (*ListTicketsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTickets not implemented")
}
func (UnimplementedOrderServiceServer) GetTableSession(context.Context, *GetTableSessionRequest) (*TableSession, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTableSession not implemented")
}
func (UnimplementedOrderServiceServer) ListActiveTableSessions(context.Context, *ListActiveTableSessionsRequest) (*ListActiveTableSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListActiveTableSessions not implemented")
}
func (UnimplementedOrderServiceServer) CloseTableSession(context.Context, *CloseTableSessionRequest) (*TableSession, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseTableSession not implemented")
}
func (UnimplementedOrderServiceServer) ListServiceRequests(context.Context, *ListServiceRequestsRequest) (*ListServiceRequestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListServiceRequests not implemented")
}
func (UnimplementedOrderServiceServer) TransitionServiceRequest(context.Context, *TransitionServiceRequestRequest) (*ServiceRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransitionServiceRequest not implemented")
}
func (UnimplementedOrderServiceServer) GetDayReport(context.Context, *GetDayReportRequest) (*DayReport, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDayReport not implemented")
}
func (UnimplementedOrderServiceServer) mustEmbedUnimplementedOrderServiceServer() {}
func (UnimplementedOrderServiceServer) testEmbeddedByValue()                      {}

// UnsafeOrderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServiceServer will
// result in compilation errors.
type UnsafeOrderServiceServer interface {
	mustEmbedUnimplementedOrderServiceServer()
}

func RegisterOrderServiceServer(s grpc.ServiceRegistrar, srv OrderServiceServer) {
	// If the following call pancis, it indicates UnimplementedOrderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderService_ServiceDesc, srv)
}

func _OrderService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_ListOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).ListOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_ListOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).ListOrders(ctx, req.(*ListOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_GetBill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetBill(ctx, req.(*GetBillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_CreateServiceRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServiceRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CreateServiceRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_CreateServiceRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CreateServiceRequest(ctx, req.(*CreateServiceRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_TransitionOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransitionOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).TransitionOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_TransitionOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).TransitionOrder(ctx, req.(*TransitionOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_TransitionOrderItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransitionOrderItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).TransitionOrderItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_TransitionOrderItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).TransitionOrderItem(ctx, req.(*TransitionOrderItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_ListTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTicketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).ListTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_ListTickets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).ListTickets(ctx, req.(*ListTicketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetTableSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTableSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetTableSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_GetTableSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetTableSession(ctx, req.(*GetTableSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_ListActiveTableSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActiveTableSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).ListActiveTableSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_ListActiveTableSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).ListActiveTableSessions(ctx, req.(*ListActiveTableSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_CloseTableSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseTableSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CloseTableSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_CloseTableSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CloseTableSession(ctx, req.(*CloseTableSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_ListServiceRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServiceRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).ListServiceRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_ListServiceRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).ListServiceRequests(ctx, req.(*ListServiceRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_TransitionServiceRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransitionServiceRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).TransitionServiceRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_TransitionServiceRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).TransitionServiceRequest(ctx, req.(*TransitionServiceRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetDayReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDayReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetDayReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_GetDayReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetDayReport(ctx, req.(*GetDayReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderService_ServiceDesc is the grpc.ServiceDesc for OrderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.v1.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _OrderService_CreateOrder_Handler,
		},
		{
			MethodName: "ListOrders",
			Handler:    _OrderService_ListOrders_Handler,
		},
		{
			MethodName: "GetBill",
			Handler:    _OrderService_GetBill_Handler,
		},
		{
			MethodName: "CreateServiceRequest",
			Handler:    _OrderService_CreateServiceRequest_Handler,
		},
		{
			MethodName: "TransitionOrder",
			Handler:    _OrderService_TransitionOrder_Handler,
		},
		{
			MethodName: "TransitionOrderItem",
			Handler:    _OrderService_TransitionOrderItem_Handler,
		},
		{
			MethodName: "ListTickets",
			Handler:    _OrderService_ListTickets_Handler,
		},
		{
			MethodName: "GetTableSession",
			Handler:    _OrderService_GetTableSession_Handler,
		},
		{
			MethodName: "ListActiveTableSessions",
			Handler:    _OrderService_ListActiveTableSessions_Handler,
		},
		{
			MethodName: "CloseTableSession",
			Handler:    _OrderService_CloseTableSession_Handler,
		},
		{
			MethodName: "ListServiceRequests",
			Handler:    _OrderService_ListServiceRequests_Handler,
		},
		{
			MethodName: "TransitionServiceRequest",
			Handler:    _OrderService_TransitionServiceRequest_Handler,
		},
		{
			MethodName: "GetDayReport",
			Handler:    _OrderService_GetDayReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
