// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: catalog.proto

package server

import (
	"context"

	"github.com/menli02/QR-menu/proto/catalog/v1"
	"github.com/menli02/QR-menu/services/catalog/internal/logic/catalogservice"
	"github.com/menli02/QR-menu/services/catalog/internal/svc"
)

type CatalogServiceServer struct {
	svcCtx *svc.ServiceContext
	v1_catalogpb.UnimplementedCatalogServiceServer
}

func NewCatalogServiceServer(svcCtx *svc.ServiceContext) *CatalogServiceServer {
	return &CatalogServiceServer{
		svcCtx: svcCtx,
	}
}

// GetMenu returns the full active, visible, in-locale menu for one venue
func (s *CatalogServiceServer) GetMenu(ctx context.Context, in *v1_catalogpb.GetMenuRequest) (*v1_catalogpb.GetMenuResponse, error) {
	l := catalogservicelogic.NewGetMenuLogic(ctx, s.svcCtx)
	return l.GetMenu(in)
}

// ResolveOrderItems re-prices and validates availability of requested items
func (s *CatalogServiceServer) ResolveOrderItems(ctx context.Context, in *v1_catalogpb.ResolveOrderItemsRequest) (*v1_catalogpb.ResolveOrderItemsResponse, error) {
	l := catalogservicelogic.NewResolveOrderItemsLogic(ctx, s.svcCtx)
	return l.ResolveOrderItems(in)
}

// ResolveTable validates a QR table_code + HMAC signature and returns the
func (s *CatalogServiceServer) ResolveTable(ctx context.Context, in *v1_catalogpb.ResolveTableRequest) (*v1_catalogpb.ResolveTableResponse, error) {
	l := catalogservicelogic.NewResolveTableLogic(ctx, s.svcCtx)
	return l.ResolveTable(in)
}

// ResolveVenueBySlug maps a public venue slug to its id.
func (s *CatalogServiceServer) ResolveVenueBySlug(ctx context.Context, in *v1_catalogpb.ResolveVenueBySlugRequest) (*v1_catalogpb.ResolveVenueBySlugResponse, error) {
	l := catalogservicelogic.NewResolveVenueBySlugLogic(ctx, s.svcCtx)
	return l.ResolveVenueBySlug(in)
}

// SetItemAvailability toggles the stop-list ("86") state of a menu item.
func (s *CatalogServiceServer) SetItemAvailability(ctx context.Context, in *v1_catalogpb.SetItemAvailabilityRequest) (*v1_catalogpb.SetItemAvailabilityResponse, error) {
	l := catalogservicelogic.NewSetItemAvailabilityLogic(ctx, s.svcCtx)
	return l.SetItemAvailability(in)
}

func (s *CatalogServiceServer) GetVenueSettings(ctx context.Context, in *v1_catalogpb.GetVenueSettingsRequest) (*v1_catalogpb.VenueSettings, error) {
	l := catalogservicelogic.NewGetVenueSettingsLogic(ctx, s.svcCtx)
	return l.GetVenueSettings(in)
}

func (s *CatalogServiceServer) UpdateVenueSettings(ctx context.Context, in *v1_catalogpb.UpdateVenueSettingsRequest) (*v1_catalogpb.VenueSettings, error) {
	l := catalogservicelogic.NewUpdateVenueSettingsLogic(ctx, s.svcCtx)
	return l.UpdateVenueSettings(in)
}

func (s *CatalogServiceServer) ListHalls(ctx context.Context, in *v1_catalogpb.ListHallsRequest) (*v1_catalogpb.ListHallsResponse, error) {
	l := catalogservicelogic.NewListHallsLogic(ctx, s.svcCtx)
	return l.ListHalls(in)
}

func (s *CatalogServiceServer) CreateHall(ctx context.Context, in *v1_catalogpb.CreateHallRequest) (*v1_catalogpb.Hall, error) {
	l := catalogservicelogic.NewCreateHallLogic(ctx, s.svcCtx)
	return l.CreateHall(in)
}

func (s *CatalogServiceServer) UpdateHall(ctx context.Context, in *v1_catalogpb.UpdateHallRequest) (*v1_catalogpb.Hall, error) {
	l := catalogservicelogic.NewUpdateHallLogic(ctx, s.svcCtx)
	return l.UpdateHall(in)
}

func (s *CatalogServiceServer) DeleteHall(ctx context.Context, in *v1_catalogpb.DeleteHallRequest) (*v1_catalogpb.DeleteHallResponse, error) {
	l := catalogservicelogic.NewDeleteHallLogic(ctx, s.svcCtx)
	return l.DeleteHall(in)
}

func (s *CatalogServiceServer) ListTables(ctx context.Context, in *v1_catalogpb.ListTablesRequest) (*v1_catalogpb.ListTablesResponse, error) {
	l := catalogservicelogic.NewListTablesLogic(ctx, s.svcCtx)
	return l.ListTables(in)
}

func (s *CatalogServiceServer) CreateTable(ctx context.Context, in *v1_catalogpb.CreateTableRequest) (*v1_catalogpb.Table, error) {
	l := catalogservicelogic.NewCreateTableLogic(ctx, s.svcCtx)
	return l.CreateTable(in)
}

func (s *CatalogServiceServer) UpdateTable(ctx context.Context, in *v1_catalogpb.UpdateTableRequest) (*v1_catalogpb.Table, error) {
	l := catalogservicelogic.NewUpdateTableLogic(ctx, s.svcCtx)
	return l.UpdateTable(in)
}

func (s *CatalogServiceServer) DeleteTable(ctx context.Context, in *v1_catalogpb.DeleteTableRequest) (*v1_catalogpb.DeleteTableResponse, error) {
	l := catalogservicelogic.NewDeleteTableLogic(ctx, s.svcCtx)
	return l.DeleteTable(in)
}

// RotateVenueQRKey issues a new HMAC key_version for QR signing; the
func (s *CatalogServiceServer) RotateVenueQRKey(ctx context.Context, in *v1_catalogpb.RotateVenueQRKeyRequest) (*v1_catalogpb.RotateVenueQRKeyResponse, error) {
	l := catalogservicelogic.NewRotateVenueQRKeyLogic(ctx, s.svcCtx)
	return l.RotateVenueQRKey(in)
}

func (s *CatalogServiceServer) ListCategories(ctx context.Context, in *v1_catalogpb.ListCategoriesRequest) (*v1_catalogpb.ListCategoriesResponse, error) {
	l := catalogservicelogic.NewListCategoriesLogic(ctx, s.svcCtx)
	return l.ListCategories(in)
}

func (s *CatalogServiceServer) CreateCategory(ctx context.Context, in *v1_catalogpb.CreateCategoryRequest) (*v1_catalogpb.Category, error) {
	l := catalogservicelogic.NewCreateCategoryLogic(ctx, s.svcCtx)
	return l.CreateCategory(in)
}

func (s *CatalogServiceServer) UpdateCategory(ctx context.Context, in *v1_catalogpb.UpdateCategoryRequest) (*v1_catalogpb.Category, error) {
	l := catalogservicelogic.NewUpdateCategoryLogic(ctx, s.svcCtx)
	return l.UpdateCategory(in)
}

func (s *CatalogServiceServer) DeleteCategory(ctx context.Context, in *v1_catalogpb.DeleteCategoryRequest) (*v1_catalogpb.DeleteCategoryResponse, error) {
	l := catalogservicelogic.NewDeleteCategoryLogic(ctx, s.svcCtx)
	return l.DeleteCategory(in)
}

func (s *CatalogServiceServer) ListMenuItems(ctx context.Context, in *v1_catalogpb.ListMenuItemsRequest) (*v1_catalogpb.ListMenuItemsResponse, error) {
	l := catalogservicelogic.NewListMenuItemsLogic(ctx, s.svcCtx)
	return l.ListMenuItems(in)
}

func (s *CatalogServiceServer) CreateMenuItem(ctx context.Context, in *v1_catalogpb.CreateMenuItemRequest) (*v1_catalogpb.MenuItem, error) {
	l := catalogservicelogic.NewCreateMenuItemLogic(ctx, s.svcCtx)
	return l.CreateMenuItem(in)
}

func (s *CatalogServiceServer) UpdateMenuItem(ctx context.Context, in *v1_catalogpb.UpdateMenuItemRequest) (*v1_catalogpb.MenuItem, error) {
	l := catalogservicelogic.NewUpdateMenuItemLogic(ctx, s.svcCtx)
	return l.UpdateMenuItem(in)
}

func (s *CatalogServiceServer) DeleteMenuItem(ctx context.Context, in *v1_catalogpb.DeleteMenuItemRequest) (*v1_catalogpb.DeleteMenuItemResponse, error) {
	l := catalogservicelogic.NewDeleteMenuItemLogic(ctx, s.svcCtx)
	return l.DeleteMenuItem(in)
}

func (s *CatalogServiceServer) CreateModifierGroup(ctx context.Context, in *v1_catalogpb.CreateModifierGroupRequest) (*v1_catalogpb.ModifierGroup, error) {
	l := catalogservicelogic.NewCreateModifierGroupLogic(ctx, s.svcCtx)
	return l.CreateModifierGroup(in)
}

func (s *CatalogServiceServer) UpdateModifierGroup(ctx context.Context, in *v1_catalogpb.UpdateModifierGroupRequest) (*v1_catalogpb.ModifierGroup, error) {
	l := catalogservicelogic.NewUpdateModifierGroupLogic(ctx, s.svcCtx)
	return l.UpdateModifierGroup(in)
}

func (s *CatalogServiceServer) DeleteModifierGroup(ctx context.Context, in *v1_catalogpb.DeleteModifierGroupRequest) (*v1_catalogpb.DeleteModifierGroupResponse, error) {
	l := catalogservicelogic.NewDeleteModifierGroupLogic(ctx, s.svcCtx)
	return l.DeleteModifierGroup(in)
}
