// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type Bill struct {
	TableSessionId     string         `json:"tableSessionId"`
	LineItems          []BillLineItem `json:"lineItems"`
	SubtotalMinor      int64          `json:"subtotalMinor"`
	ServiceChargeBps   int32          `json:"serviceChargeBps"`
	ServiceChargeMinor int64          `json:"serviceChargeMinor"`
	TotalMinor         int64          `json:"totalMinor"`
	Currency           string         `json:"currency"`
}

type BillLineItem struct {
	Name           string `json:"name"`
	Qty            int32  `json:"qty"`
	UnitPrice      Money  `json:"unitPrice"`
	LineTotalMinor int64  `json:"lineTotalMinor"`
}

type CancelGuestOrderReq struct {
	Id     string `path:"id"`
	Reason string `json:"reason,optional"`
}

type Category struct {
	Id        string `json:"id"`
	Name      string `json:"name"`
	SortOrder int32  `json:"sortOrder"`
	IsVisible bool   `json:"isVisible"`
	ImageUrl  string `json:"imageUrl"`
}

type CloseTableSessionReq struct {
	Id            string `path:"id"`
	PaymentMethod string `json:"paymentMethod"` // cash | card_terminal | other
}

type CreateCategoryReq struct {
	Locale    string `json:"locale"`
	Name      string `json:"name"`
	SortOrder int32  `json:"sortOrder,optional"`
	IsVisible bool   `json:"isVisible,optional"`
	ImageUrl  string `json:"imageUrl,optional"`
}

type CreateGuestOrderReq struct {
	Items              []OrderItemReq `json:"items"`
	ExpectedTotalMinor int64          `json:"expectedTotalMinor,optional"`
}

type CreateGuestServiceRequestReq struct {
	Type string `json:"type"` // call_waiter | request_bill
	Note string `json:"note,optional"`
}

type CreateHallReq struct {
	Name      string `json:"name"`
	SortOrder int32  `json:"sortOrder,optional"`
}

type CreateMenuItemReq struct {
	CategoryId  string   `json:"categoryId"`
	Locale      string   `json:"locale"`
	Name        string   `json:"name"`
	Description string   `json:"description,optional"`
	BasePrice   Money    `json:"basePrice"`
	ImageUrl    string   `json:"imageUrl,optional"`
	Allergens   []string `json:"allergens,optional"`
	SortOrder   int32    `json:"sortOrder,optional"`
}

type CreateModifierGroupReq struct {
	ItemId    string           `path:"itemId"`
	Locale    string           `json:"locale"`
	Name      string           `json:"name"`
	MinSelect int32            `json:"minSelect"`
	MaxSelect int32            `json:"maxSelect"`
	Required  bool             `json:"required"`
	Options   []ModifierOption `json:"options,optional"`
}

type CreateStaffReq struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Role     string `json:"role"`
}

type CreateTableReq struct {
	HallId string `json:"hallId"`
	Label  string `json:"label"`
	Seats  int32  `json:"seats,optional"`
}

type DayReport struct {
	BusinessDate         string    `json:"businessDate"`
	OrdersCount          int32     `json:"ordersCount"`
	RevenueMinor         int64     `json:"revenueMinor"`
	Currency             string    `json:"currency"`
	AverageTicketMinor   int64     `json:"averageTicketMinor"`
	TopItems             []TopItem `json:"topItems"`
	AverageAcceptSeconds float64   `json:"averageAcceptSeconds"`
	AverageCookSeconds   float64   `json:"averageCookSeconds"`
}

type DeleteCategoryReq struct {
	Id string `path:"id"`
}

type DeleteHallReq struct {
	Id string `path:"id"`
}

type DeleteMenuItemReq struct {
	Id string `path:"id"`
}

type DeleteModifierGroupReq struct {
	ItemId  string `path:"itemId"`
	GroupId string `path:"groupId"`
}

type DeleteStaffReq struct {
	Id string `path:"id"`
}

type DeleteTableReq struct {
	Id string `path:"id"`
}

type DeletedResp struct {
	Deleted bool `json:"deleted"`
}

type ExchangeGuestSessionReq struct {
	VenueSlug string `json:"venueSlug"`
	TableCode string `json:"tableCode"`
	Sig       string `json:"sig"`
}

type ExchangeGuestSessionResp struct {
	AccessToken    string `json:"accessToken"`
	TokenType      string `json:"tokenType"`
	ExpiresAt      string `json:"expiresAt"`
	VenueId        string `json:"venueId"`
	TableId        string `json:"tableId"`
	GuestSessionId string `json:"guestSessionId"`
}

type GetDayReportReq struct {
	Date string `form:"date"` // YYYY-MM-DD
}

type GetGuestMenuReq struct {
	Locale string `form:"locale,optional"`
}

type GetGuestMenuResp struct {
	VenueId     string         `json:"venueId"`
	MenuVersion string         `json:"menuVersion"`
	Currency    string         `json:"currency"`
	Categories  []MenuCategory `json:"categories"`
}

type GetTableSessionBillReq struct {
	Id string `path:"id"`
}

type Hall struct {
	Id        string `json:"id"`
	Name      string `json:"name"`
	SortOrder int32  `json:"sortOrder"`
	IsActive  bool   `json:"isActive"`
}

type ListCategoriesResp struct {
	Categories []Category `json:"categories"`
}

type FloorTable struct {
	Id             string `json:"id"`
	HallId         string `json:"hallId"`
	Label          string `json:"label"`
	Seats          int32  `json:"seats"`
	IsActive       bool   `json:"isActive"`
	Occupied       bool   `json:"occupied"`
	TableSessionId string `json:"tableSessionId,omitempty"`
	OpenedAt       string `json:"openedAt,omitempty"`
	TotalMinor     int64  `json:"totalMinor"`
	Currency       string `json:"currency,omitempty"`
}

type ListFloorTablesResp struct {
	Tables []FloorTable `json:"tables"`
}

type ListGuestOrdersResp struct {
	Orders []Order `json:"orders"`
}

type ListHallsResp struct {
	Halls []Hall `json:"halls"`
}

type ListMenuItemsReq struct {
	CategoryId string `form:"categoryId,optional"`
	Cursor     string `form:"cursor,optional"`
	PageSize   int32  `form:"pageSize,optional"`
}

type ListMenuItemsResp struct {
	Items      []MenuItem `json:"items"`
	NextCursor string     `json:"nextCursor"`
}

type ListServiceRequestsReq struct {
	Status string `form:"status,optional"` // open (default) | all
}

type ListServiceRequestsResp struct {
	Requests []ServiceRequest `json:"requests"`
}

type ListStaffReq struct {
	Cursor   string `form:"cursor,optional"`
	PageSize int32  `form:"pageSize,optional"`
}

type ListStaffResp struct {
	Staff      []Staff `json:"staff"`
	NextCursor string  `json:"nextCursor"`
}

type ListTablesReq struct {
	HallId   string `form:"hallId,optional"`
	Cursor   string `form:"cursor,optional"`
	PageSize int32  `form:"pageSize,optional"`
}

type ListTablesResp struct {
	Tables     []Table `json:"tables"`
	NextCursor string  `json:"nextCursor"`
}

type ListTicketsReq struct {
	Status string `form:"status,optional"` // active (default) | all
}

type ListTicketsResp struct {
	Orders []Order `json:"orders"`
}

type LoginReq struct {
	VenueSlug string `json:"venueSlug"`
	Email     string `json:"email"`
	Password  string `json:"password"`
}

type LogoutReq struct {
	RefreshToken string `json:"refreshToken"`
}

type LogoutResp struct {
	Revoked bool `json:"revoked"`
}

type MenuCategory struct {
	Id        string     `json:"id"`
	Name      string     `json:"name"`
	SortOrder int32      `json:"sortOrder"`
	Items     []MenuItem `json:"items"`
}

type MenuItem struct {
	Id             string          `json:"id"`
	CategoryId     string          `json:"categoryId"`
	Name           string          `json:"name"`
	Description    string          `json:"description"`
	BasePrice      Money           `json:"basePrice"`
	ImageUrl       string          `json:"imageUrl"`
	Allergens      []string        `json:"allergens"`
	IsAvailable    bool            `json:"isAvailable"`
	SortOrder      int32           `json:"sortOrder"`
	ModifierGroups []ModifierGroup `json:"modifierGroups"`
}

type ModifierGroup struct {
	Id        string           `json:"id"`
	Name      string           `json:"name"`
	MinSelect int32            `json:"minSelect"`
	MaxSelect int32            `json:"maxSelect"`
	Required  bool             `json:"required"`
	Options   []ModifierOption `json:"options"`
}

type ModifierOption struct {
	Id         string `json:"id"`
	Name       string `json:"name"`
	PriceDelta Money  `json:"priceDelta"`
}

type Money struct {
	AmountMinor int64  `json:"amountMinor"`
	Currency    string `json:"currency"`
}

type Order struct {
	Id             string      `json:"id"`
	TableId        string      `json:"tableId"`
	TableSessionId string      `json:"tableSessionId"`
	Number         string      `json:"number"`
	Status         string      `json:"status"`
	Items          []OrderItem `json:"items"`
	TotalMinor     int64       `json:"totalMinor"`
	Currency       string      `json:"currency"`
	PlacedAt       string      `json:"placedAt"`
	UpdatedAt      string      `json:"updatedAt"`
}

type OrderItem struct {
	Id             string              `json:"id"`
	MenuItemId     string              `json:"menuItemId"`
	Name           string              `json:"name"`
	UnitPrice      Money               `json:"unitPrice"`
	Qty            int32               `json:"qty"`
	Modifiers      []OrderItemModifier `json:"modifiers"`
	Comment        string              `json:"comment"`
	Status         string              `json:"status"`
	LineTotalMinor int64               `json:"lineTotalMinor"`
}

type OrderItemModifier struct {
	OptionId   string `json:"optionId"`
	Name       string `json:"name"`
	PriceDelta Money  `json:"priceDelta"`
}

type OrderItemReq struct {
	ItemId            string   `json:"itemId"`
	Qty               int32    `json:"qty"`
	ModifierOptionIds []string `json:"modifierOptionIds,optional"`
	Comment           string   `json:"comment,optional"`
}

type RefreshReq struct {
	RefreshToken string `json:"refreshToken"`
}

type RotateVenueQrKeyResp struct {
	NewKeyVersion        int32  `json:"newKeyVersion"`
	PreviousKeyVersion   int32  `json:"previousKeyVersion"`
	PreviousKeyExpiresAt string `json:"previousKeyExpiresAt"`
}

type ServiceRequest struct {
	Id             string `json:"id"`
	TableId        string `json:"tableId"`
	TableSessionId string `json:"tableSessionId"`
	Type           string `json:"type"`   // call_waiter | request_bill
	Status         string `json:"status"` // open | acknowledged | resolved | expired
	Note           string `json:"note,omitempty"`
	CreatedAt      string `json:"createdAt"`
}

type SetItemAvailabilityReq struct {
	ItemId      string `path:"itemId"`
	IsAvailable bool   `json:"isAvailable"`
}

type Staff struct {
	Id       string `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Role     string `json:"role"` // admin | manager | waiter | cook
	IsActive bool   `json:"isActive"`
}

type Table struct {
	Id         string `json:"id"`
	HallId     string `json:"hallId"`
	Label      string `json:"label"`
	Seats      int32  `json:"seats"`
	IsActive   bool   `json:"isActive"`
	TableCode  string `json:"tableCode"`
	KeyVersion int32  `json:"keyVersion"`
}

type TableSession struct {
	Id            string `json:"id"`
	TableId       string `json:"tableId"`
	Status        string `json:"status"`
	OpenedAt      string `json:"openedAt"`
	ClosedAt      string `json:"closedAt,omitempty"`
	PaymentMethod string `json:"paymentMethod,omitempty"`
	TotalMinor    int64  `json:"totalMinor"`
	Currency      string `json:"currency"`
}

type TokenResp struct {
	AccessToken           string `json:"accessToken"`
	RefreshToken          string `json:"refreshToken"`
	TokenType             string `json:"tokenType"`
	AccessTokenExpiresAt  string `json:"accessTokenExpiresAt"`
	RefreshTokenExpiresAt string `json:"refreshTokenExpiresAt"`
}

type TopItem struct {
	Name         string `json:"name"`
	QtySold      int32  `json:"qtySold"`
	RevenueMinor int64  `json:"revenueMinor"`
}

type TransitionOrderItemReq struct {
	Id      string `path:"id"`
	OrderId string `json:"orderId"`
	To      string `json:"to"`
	Reason  string `json:"reason,optional"`
}

type TransitionOrderReq struct {
	Id     string `path:"id"`
	To     string `json:"to"`
	Reason string `json:"reason,optional"`
}

type TransitionServiceRequestReq struct {
	Id string `path:"id"`
	To string `json:"to"`
}

type UpdateCategoryReq struct {
	Id        string `path:"id"`
	Locale    string `json:"locale"`
	Name      string `json:"name"`
	SortOrder int32  `json:"sortOrder"`
	IsVisible bool   `json:"isVisible"`
	ImageUrl  string `json:"imageUrl,optional"`
}

type UpdateHallReq struct {
	Id        string `path:"id"`
	Name      string `json:"name"`
	SortOrder int32  `json:"sortOrder"`
	IsActive  bool   `json:"isActive"`
}

type UpdateMenuItemReq struct {
	Id          string   `path:"id"`
	CategoryId  string   `json:"categoryId"`
	Locale      string   `json:"locale"`
	Name        string   `json:"name"`
	Description string   `json:"description,optional"`
	BasePrice   Money    `json:"basePrice"`
	ImageUrl    string   `json:"imageUrl,optional"`
	Allergens   []string `json:"allergens,optional"`
	IsActive    bool     `json:"isActive"`
	SortOrder   int32    `json:"sortOrder"`
}

type UpdateModifierGroupReq struct {
	ItemId    string           `path:"itemId"`
	GroupId   string           `path:"groupId"`
	Locale    string           `json:"locale"`
	Name      string           `json:"name"`
	MinSelect int32            `json:"minSelect"`
	MaxSelect int32            `json:"maxSelect"`
	Required  bool             `json:"required"`
	Options   []ModifierOption `json:"options,optional"`
}

type UpdateStaffReq struct {
	Id       string `path:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	Role     string `json:"role"`
	IsActive bool   `json:"isActive"`
}

type UpdateTableReq struct {
	Id       string `path:"id"`
	HallId   string `json:"hallId"`
	Label    string `json:"label"`
	Seats    int32  `json:"seats"`
	IsActive bool   `json:"isActive"`
}

type UpdateVenueSettingsReq struct {
	Name                     string   `json:"name"`
	LogoUrl                  string   `json:"logoUrl,optional"`
	Currency                 string   `json:"currency"`
	Locales                  []string `json:"locales"`
	DefaultLocale            string   `json:"defaultLocale"`
	Timezone                 string   `json:"timezone"`
	ServiceChargeBps         int32    `json:"serviceChargeBps"`
	CancelWindowSeconds      int32    `json:"cancelWindowSeconds"`
	KdsAmberThresholdSeconds int32    `json:"kdsAmberThresholdSeconds"`
	KdsRedThresholdSeconds   int32    `json:"kdsRedThresholdSeconds"`
}

type VenueSettings struct {
	VenueId                  string   `json:"venueId"`
	Name                     string   `json:"name"`
	LogoUrl                  string   `json:"logoUrl"`
	Currency                 string   `json:"currency"`
	Locales                  []string `json:"locales"`
	DefaultLocale            string   `json:"defaultLocale"`
	Timezone                 string   `json:"timezone"`
	ServiceChargeBps         int32    `json:"serviceChargeBps"`
	CancelWindowSeconds      int32    `json:"cancelWindowSeconds"`
	KdsAmberThresholdSeconds int32    `json:"kdsAmberThresholdSeconds"`
	KdsRedThresholdSeconds   int32    `json:"kdsRedThresholdSeconds"`
}
