// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: catalog.proto

package catalogservice

import (
	"context"

	"github.com/menli02/QR-menu/proto/catalog/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Category                    = v1_catalogpb.Category
	CreateCategoryRequest       = v1_catalogpb.CreateCategoryRequest
	CreateHallRequest           = v1_catalogpb.CreateHallRequest
	CreateMenuItemRequest       = v1_catalogpb.CreateMenuItemRequest
	CreateModifierGroupRequest  = v1_catalogpb.CreateModifierGroupRequest
	CreateTableRequest          = v1_catalogpb.CreateTableRequest
	DeleteCategoryRequest       = v1_catalogpb.DeleteCategoryRequest
	DeleteCategoryResponse      = v1_catalogpb.DeleteCategoryResponse
	DeleteHallRequest           = v1_catalogpb.DeleteHallRequest
	DeleteHallResponse          = v1_catalogpb.DeleteHallResponse
	DeleteMenuItemRequest       = v1_catalogpb.DeleteMenuItemRequest
	DeleteMenuItemResponse      = v1_catalogpb.DeleteMenuItemResponse
	DeleteModifierGroupRequest  = v1_catalogpb.DeleteModifierGroupRequest
	DeleteModifierGroupResponse = v1_catalogpb.DeleteModifierGroupResponse
	DeleteTableRequest          = v1_catalogpb.DeleteTableRequest
	DeleteTableResponse         = v1_catalogpb.DeleteTableResponse
	GetMenuRequest              = v1_catalogpb.GetMenuRequest
	GetMenuResponse             = v1_catalogpb.GetMenuResponse
	GetVenueSettingsRequest     = v1_catalogpb.GetVenueSettingsRequest
	Hall                        = v1_catalogpb.Hall
	ListCategoriesRequest       = v1_catalogpb.ListCategoriesRequest
	ListCategoriesResponse      = v1_catalogpb.ListCategoriesResponse
	ListHallsRequest            = v1_catalogpb.ListHallsRequest
	ListHallsResponse           = v1_catalogpb.ListHallsResponse
	ListMenuItemsRequest        = v1_catalogpb.ListMenuItemsRequest
	ListMenuItemsResponse       = v1_catalogpb.ListMenuItemsResponse
	ListTablesRequest           = v1_catalogpb.ListTablesRequest
	ListTablesResponse          = v1_catalogpb.ListTablesResponse
	MenuItem                    = v1_catalogpb.MenuItem
	ModifierGroup               = v1_catalogpb.ModifierGroup
	ResolveOrderItemsRequest    = v1_catalogpb.ResolveOrderItemsRequest
	ResolveOrderItemsResponse   = v1_catalogpb.ResolveOrderItemsResponse
	ResolveTableRequest         = v1_catalogpb.ResolveTableRequest
	ResolveTableResponse        = v1_catalogpb.ResolveTableResponse
	RotateVenueQRKeyRequest     = v1_catalogpb.RotateVenueQRKeyRequest
	RotateVenueQRKeyResponse    = v1_catalogpb.RotateVenueQRKeyResponse
	SetItemAvailabilityRequest  = v1_catalogpb.SetItemAvailabilityRequest
	SetItemAvailabilityResponse = v1_catalogpb.SetItemAvailabilityResponse
	Table                       = v1_catalogpb.Table
	UpdateCategoryRequest       = v1_catalogpb.UpdateCategoryRequest
	UpdateHallRequest           = v1_catalogpb.UpdateHallRequest
	UpdateMenuItemRequest       = v1_catalogpb.UpdateMenuItemRequest
	UpdateModifierGroupRequest  = v1_catalogpb.UpdateModifierGroupRequest
	UpdateTableRequest          = v1_catalogpb.UpdateTableRequest
	UpdateVenueSettingsRequest  = v1_catalogpb.UpdateVenueSettingsRequest
	VenueSettings               = v1_catalogpb.VenueSettings

	CatalogService interface {
		// GetMenu returns the full active, visible, in-locale menu for one venue
		GetMenu(ctx context.Context, in *GetMenuRequest, opts ...grpc.CallOption) (*GetMenuResponse, error)
		// ResolveOrderItems re-prices and validates availability of requested items
		ResolveOrderItems(ctx context.Context, in *ResolveOrderItemsRequest, opts ...grpc.CallOption) (*ResolveOrderItemsResponse, error)
		// ResolveTable validates a QR table_code + HMAC signature and returns the
		ResolveTable(ctx context.Context, in *ResolveTableRequest, opts ...grpc.CallOption) (*ResolveTableResponse, error)
		// SetItemAvailability toggles the stop-list ("86") state of a menu item.
		SetItemAvailability(ctx context.Context, in *SetItemAvailabilityRequest, opts ...grpc.CallOption) (*SetItemAvailabilityResponse, error)
		GetVenueSettings(ctx context.Context, in *GetVenueSettingsRequest, opts ...grpc.CallOption) (*VenueSettings, error)
		UpdateVenueSettings(ctx context.Context, in *UpdateVenueSettingsRequest, opts ...grpc.CallOption) (*VenueSettings, error)
		ListHalls(ctx context.Context, in *ListHallsRequest, opts ...grpc.CallOption) (*ListHallsResponse, error)
		CreateHall(ctx context.Context, in *CreateHallRequest, opts ...grpc.CallOption) (*Hall, error)
		UpdateHall(ctx context.Context, in *UpdateHallRequest, opts ...grpc.CallOption) (*Hall, error)
		DeleteHall(ctx context.Context, in *DeleteHallRequest, opts ...grpc.CallOption) (*DeleteHallResponse, error)
		ListTables(ctx context.Context, in *ListTablesRequest, opts ...grpc.CallOption) (*ListTablesResponse, error)
		CreateTable(ctx context.Context, in *CreateTableRequest, opts ...grpc.CallOption) (*Table, error)
		UpdateTable(ctx context.Context, in *UpdateTableRequest, opts ...grpc.CallOption) (*Table, error)
		DeleteTable(ctx context.Context, in *DeleteTableRequest, opts ...grpc.CallOption) (*DeleteTableResponse, error)
		// RotateVenueQRKey issues a new HMAC key_version for QR signing; the
		RotateVenueQRKey(ctx context.Context, in *RotateVenueQRKeyRequest, opts ...grpc.CallOption) (*RotateVenueQRKeyResponse, error)
		ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...grpc.CallOption) (*ListCategoriesResponse, error)
		CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*Category, error)
		UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*Category, error)
		DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*DeleteCategoryResponse, error)
		ListMenuItems(ctx context.Context, in *ListMenuItemsRequest, opts ...grpc.CallOption) (*ListMenuItemsResponse, error)
		CreateMenuItem(ctx context.Context, in *CreateMenuItemRequest, opts ...grpc.CallOption) (*MenuItem, error)
		UpdateMenuItem(ctx context.Context, in *UpdateMenuItemRequest, opts ...grpc.CallOption) (*MenuItem, error)
		DeleteMenuItem(ctx context.Context, in *DeleteMenuItemRequest, opts ...grpc.CallOption) (*DeleteMenuItemResponse, error)
		CreateModifierGroup(ctx context.Context, in *CreateModifierGroupRequest, opts ...grpc.CallOption) (*ModifierGroup, error)
		UpdateModifierGroup(ctx context.Context, in *UpdateModifierGroupRequest, opts ...grpc.CallOption) (*ModifierGroup, error)
		DeleteModifierGroup(ctx context.Context, in *DeleteModifierGroupRequest, opts ...grpc.CallOption) (*DeleteModifierGroupResponse, error)
	}

	defaultCatalogService struct {
		cli zrpc.Client
	}
)

func NewCatalogService(cli zrpc.Client) CatalogService {
	return &defaultCatalogService{
		cli: cli,
	}
}

// GetMenu returns the full active, visible, in-locale menu for one venue
func (m *defaultCatalogService) GetMenu(ctx context.Context, in *GetMenuRequest, opts ...grpc.CallOption) (*GetMenuResponse, error) {
	client := v1_catalogpb.NewCatalogServiceClient(m.cli.Conn())
	return client.GetMenu(ctx, in, opts...)
}

// ResolveOrderItems re-prices and validates availability of requested items
func (m *defaultCatalogService) ResolveOrderItems(ctx context.Context, in *ResolveOrderItemsRequest, opts ...grpc.CallOption) (*ResolveOrderItemsResponse, error) {
	client := v1_catalogpb.NewCatalogServiceClient(m.cli.Conn())
	return client.ResolveOrderItems(ctx, in, opts...)
}

// ResolveTable validates a QR table_code + HMAC signature and returns the
func (m *defaultCatalogService) ResolveTable(ctx context.Context, in *ResolveTableRequest, opts ...grpc.CallOption) (*ResolveTableResponse, error) {
	client := v1_catalogpb.NewCatalogServiceClient(m.cli.Conn())
	return client.ResolveTable(ctx, in, opts...)
}

// SetItemAvailability toggles the stop-list ("86") state of a menu item.
func (m *defaultCatalogService) SetItemAvailability(ctx context.Context, in *SetItemAvailabilityRequest, opts ...grpc.CallOption) (*SetItemAvailabilityResponse, error) {
	client := v1_catalogpb.NewCatalogServiceClient(m.cli.Conn())
	return client.SetItemAvailability(ctx, in, opts...)
}

func (m *defaultCatalogService) GetVenueSettings(ctx context.Context, in *GetVenueSettingsRequest, opts ...grpc.CallOption) (*VenueSettings, error) {
	client := v1_catalogpb.NewCatalogServiceClient(m.cli.Conn())
	return client.GetVenueSettings(ctx, in, opts...)
}

func (m *defaultCatalogService) UpdateVenueSettings(ctx context.Context, in *UpdateVenueSettingsRequest, opts ...grpc.CallOption) (*VenueSettings, error) {
	client := v1_catalogpb.NewCatalogServiceClient(m.cli.Conn())
	return client.UpdateVenueSettings(ctx, in, opts...)
}

func (m *defaultCatalogService) ListHalls(ctx context.Context, in *ListHallsRequest, opts ...grpc.CallOption) (*ListHallsResponse, error) {
	client := v1_catalogpb.NewCatalogServiceClient(m.cli.Conn())
	return client.ListHalls(ctx, in, opts...)
}

func (m *defaultCatalogService) CreateHall(ctx context.Context, in *CreateHallRequest, opts ...grpc.CallOption) (*Hall, error) {
	client := v1_catalogpb.NewCatalogServiceClient(m.cli.Conn())
	return client.CreateHall(ctx, in, opts...)
}

func (m *defaultCatalogService) UpdateHall(ctx context.Context, in *UpdateHallRequest, opts ...grpc.CallOption) (*Hall, error) {
	client := v1_catalogpb.NewCatalogServiceClient(m.cli.Conn())
	return client.UpdateHall(ctx, in, opts...)
}

func (m *defaultCatalogService) DeleteHall(ctx context.Context, in *DeleteHallRequest, opts ...grpc.CallOption) (*DeleteHallResponse, error) {
	client := v1_catalogpb.NewCatalogServiceClient(m.cli.Conn())
	return client.DeleteHall(ctx, in, opts...)
}

func (m *defaultCatalogService) ListTables(ctx context.Context, in *ListTablesRequest, opts ...grpc.CallOption) (*ListTablesResponse, error) {
	client := v1_catalogpb.NewCatalogServiceClient(m.cli.Conn())
	return client.ListTables(ctx, in, opts...)
}

func (m *defaultCatalogService) CreateTable(ctx context.Context, in *CreateTableRequest, opts ...grpc.CallOption) (*Table, error) {
	client := v1_catalogpb.NewCatalogServiceClient(m.cli.Conn())
	return client.CreateTable(ctx, in, opts...)
}

func (m *defaultCatalogService) UpdateTable(ctx context.Context, in *UpdateTableRequest, opts ...grpc.CallOption) (*Table, error) {
	client := v1_catalogpb.NewCatalogServiceClient(m.cli.Conn())
	return client.UpdateTable(ctx, in, opts...)
}

func (m *defaultCatalogService) DeleteTable(ctx context.Context, in *DeleteTableRequest, opts ...grpc.CallOption) (*DeleteTableResponse, error) {
	client := v1_catalogpb.NewCatalogServiceClient(m.cli.Conn())
	return client.DeleteTable(ctx, in, opts...)
}

// RotateVenueQRKey issues a new HMAC key_version for QR signing; the
func (m *defaultCatalogService) RotateVenueQRKey(ctx context.Context, in *RotateVenueQRKeyRequest, opts ...grpc.CallOption) (*RotateVenueQRKeyResponse, error) {
	client := v1_catalogpb.NewCatalogServiceClient(m.cli.Conn())
	return client.RotateVenueQRKey(ctx, in, opts...)
}

func (m *defaultCatalogService) ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...grpc.CallOption) (*ListCategoriesResponse, error) {
	client := v1_catalogpb.NewCatalogServiceClient(m.cli.Conn())
	return client.ListCategories(ctx, in, opts...)
}

func (m *defaultCatalogService) CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*Category, error) {
	client := v1_catalogpb.NewCatalogServiceClient(m.cli.Conn())
	return client.CreateCategory(ctx, in, opts...)
}

func (m *defaultCatalogService) UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*Category, error) {
	client := v1_catalogpb.NewCatalogServiceClient(m.cli.Conn())
	return client.UpdateCategory(ctx, in, opts...)
}

func (m *defaultCatalogService) DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*DeleteCategoryResponse, error) {
	client := v1_catalogpb.NewCatalogServiceClient(m.cli.Conn())
	return client.DeleteCategory(ctx, in, opts...)
}

func (m *defaultCatalogService) ListMenuItems(ctx context.Context, in *ListMenuItemsRequest, opts ...grpc.CallOption) (*ListMenuItemsResponse, error) {
	client := v1_catalogpb.NewCatalogServiceClient(m.cli.Conn())
	return client.ListMenuItems(ctx, in, opts...)
}

func (m *defaultCatalogService) CreateMenuItem(ctx context.Context, in *CreateMenuItemRequest, opts ...grpc.CallOption) (*MenuItem, error) {
	client := v1_catalogpb.NewCatalogServiceClient(m.cli.Conn())
	return client.CreateMenuItem(ctx, in, opts...)
}

func (m *defaultCatalogService) UpdateMenuItem(ctx context.Context, in *UpdateMenuItemRequest, opts ...grpc.CallOption) (*MenuItem, error) {
	client := v1_catalogpb.NewCatalogServiceClient(m.cli.Conn())
	return client.UpdateMenuItem(ctx, in, opts...)
}

func (m *defaultCatalogService) DeleteMenuItem(ctx context.Context, in *DeleteMenuItemRequest, opts ...grpc.CallOption) (*DeleteMenuItemResponse, error) {
	client := v1_catalogpb.NewCatalogServiceClient(m.cli.Conn())
	return client.DeleteMenuItem(ctx, in, opts...)
}

func (m *defaultCatalogService) CreateModifierGroup(ctx context.Context, in *CreateModifierGroupRequest, opts ...grpc.CallOption) (*ModifierGroup, error) {
	client := v1_catalogpb.NewCatalogServiceClient(m.cli.Conn())
	return client.CreateModifierGroup(ctx, in, opts...)
}

func (m *defaultCatalogService) UpdateModifierGroup(ctx context.Context, in *UpdateModifierGroupRequest, opts ...grpc.CallOption) (*ModifierGroup, error) {
	client := v1_catalogpb.NewCatalogServiceClient(m.cli.Conn())
	return client.UpdateModifierGroup(ctx, in, opts...)
}

func (m *defaultCatalogService) DeleteModifierGroup(ctx context.Context, in *DeleteModifierGroupRequest, opts ...grpc.CallOption) (*DeleteModifierGroupResponse, error) {
	client := v1_catalogpb.NewCatalogServiceClient(m.cli.Conn())
	return client.DeleteModifierGroup(ctx, in, opts...)
}
