// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.2
// source: catalog.proto

// CatalogService owns Venue, Hall, Table, Category, MenuItem, ModifierGroup
// and ModifierOption. Read-dominated, aggressively cached. See docs/TZ.md §6, §7.1.

package v1_catalogpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CatalogService_GetMenu_FullMethodName             = "/catalog.v1.CatalogService/GetMenu"
	CatalogService_ResolveOrderItems_FullMethodName   = "/catalog.v1.CatalogService/ResolveOrderItems"
	CatalogService_ResolveTable_FullMethodName        = "/catalog.v1.CatalogService/ResolveTable"
	CatalogService_SetItemAvailability_FullMethodName = "/catalog.v1.CatalogService/SetItemAvailability"
	CatalogService_GetVenueSettings_FullMethodName    = "/catalog.v1.CatalogService/GetVenueSettings"
	CatalogService_UpdateVenueSettings_FullMethodName = "/catalog.v1.CatalogService/UpdateVenueSettings"
	CatalogService_ListHalls_FullMethodName           = "/catalog.v1.CatalogService/ListHalls"
	CatalogService_CreateHall_FullMethodName          = "/catalog.v1.CatalogService/CreateHall"
	CatalogService_UpdateHall_FullMethodName          = "/catalog.v1.CatalogService/UpdateHall"
	CatalogService_DeleteHall_FullMethodName          = "/catalog.v1.CatalogService/DeleteHall"
	CatalogService_ListTables_FullMethodName          = "/catalog.v1.CatalogService/ListTables"
	CatalogService_CreateTable_FullMethodName         = "/catalog.v1.CatalogService/CreateTable"
	CatalogService_UpdateTable_FullMethodName         = "/catalog.v1.CatalogService/UpdateTable"
	CatalogService_DeleteTable_FullMethodName         = "/catalog.v1.CatalogService/DeleteTable"
	CatalogService_RotateVenueQRKey_FullMethodName    = "/catalog.v1.CatalogService/RotateVenueQRKey"
	CatalogService_ListCategories_FullMethodName      = "/catalog.v1.CatalogService/ListCategories"
	CatalogService_CreateCategory_FullMethodName      = "/catalog.v1.CatalogService/CreateCategory"
	CatalogService_UpdateCategory_FullMethodName      = "/catalog.v1.CatalogService/UpdateCategory"
	CatalogService_DeleteCategory_FullMethodName      = "/catalog.v1.CatalogService/DeleteCategory"
	CatalogService_ListMenuItems_FullMethodName       = "/catalog.v1.CatalogService/ListMenuItems"
	CatalogService_CreateMenuItem_FullMethodName      = "/catalog.v1.CatalogService/CreateMenuItem"
	CatalogService_UpdateMenuItem_FullMethodName      = "/catalog.v1.CatalogService/UpdateMenuItem"
	CatalogService_DeleteMenuItem_FullMethodName      = "/catalog.v1.CatalogService/DeleteMenuItem"
	CatalogService_CreateModifierGroup_FullMethodName = "/catalog.v1.CatalogService/CreateModifierGroup"
	CatalogService_UpdateModifierGroup_FullMethodName = "/catalog.v1.CatalogService/UpdateModifierGroup"
	CatalogService_DeleteModifierGroup_FullMethodName = "/catalog.v1.CatalogService/DeleteModifierGroup"
)

// CatalogServiceClient is the client API for CatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatalogServiceClient interface {
	// GetMenu returns the full active, visible, in-locale menu for one venue
	// in a single response. Cacheable by menu_version (docs/TZ.md FR-C5, FR-C6).
	GetMenu(ctx context.Context, in *GetMenuRequest, opts ...grpc.CallOption) (*GetMenuResponse, error)
	// ResolveOrderItems re-prices and validates availability of requested items
	// server-side; the client-displayed cart is never trusted (docs/TZ.md FR-O3).
	ResolveOrderItems(ctx context.Context, in *ResolveOrderItemsRequest, opts ...grpc.CallOption) (*ResolveOrderItemsResponse, error)
	// ResolveTable validates a QR table_code + HMAC signature and returns the
	// venue/table it maps to (docs/TZ.md FR-T2, FR-T4).
	ResolveTable(ctx context.Context, in *ResolveTableRequest, opts ...grpc.CallOption) (*ResolveTableResponse, error)
	// SetItemAvailability toggles the stop-list ("86") state of a menu item.
	SetItemAvailability(ctx context.Context, in *SetItemAvailabilityRequest, opts ...grpc.CallOption) (*SetItemAvailabilityResponse, error)
	GetVenueSettings(ctx context.Context, in *GetVenueSettingsRequest, opts ...grpc.CallOption) (*VenueSettings, error)
	UpdateVenueSettings(ctx context.Context, in *UpdateVenueSettingsRequest, opts ...grpc.CallOption) (*VenueSettings, error)
	ListHalls(ctx context.Context, in *ListHallsRequest, opts ...grpc.CallOption) (*ListHallsResponse, error)
	CreateHall(ctx context.Context, in *CreateHallRequest, opts ...grpc.CallOption) (*Hall, error)
	UpdateHall(ctx context.Context, in *UpdateHallRequest, opts ...grpc.CallOption) (*Hall, error)
	DeleteHall(ctx context.Context, in *DeleteHallRequest, opts ...grpc.CallOption) (*DeleteHallResponse, error)
	ListTables(ctx context.Context, in *ListTablesRequest, opts ...grpc.CallOption) (*ListTablesResponse, error)
	CreateTable(ctx context.Context, in *CreateTableRequest, opts ...grpc.CallOption) (*Table, error)
	UpdateTable(ctx context.Context, in *UpdateTableRequest, opts ...grpc.CallOption) (*Table, error)
	DeleteTable(ctx context.Context, in *DeleteTableRequest, opts ...grpc.CallOption) (*DeleteTableResponse, error)
	// RotateVenueQRKey issues a new HMAC key_version for QR signing; the
	// previous version stays valid for the venue's configured grace period
	// (docs/TZ.md FR-T4).
	RotateVenueQRKey(ctx context.Context, in *RotateVenueQRKeyRequest, opts ...grpc.CallOption) (*RotateVenueQRKeyResponse, error)
	ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...grpc.CallOption) (*ListCategoriesResponse, error)
	CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*Category, error)
	UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*Category, error)
	DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*DeleteCategoryResponse, error)
	ListMenuItems(ctx context.Context, in *ListMenuItemsRequest, opts ...grpc.CallOption) (*ListMenuItemsResponse, error)
	CreateMenuItem(ctx context.Context, in *CreateMenuItemRequest, opts ...grpc.CallOption) (*MenuItem, error)
	UpdateMenuItem(ctx context.Context, in *UpdateMenuItemRequest, opts ...grpc.CallOption) (*MenuItem, error)
	DeleteMenuItem(ctx context.Context, in *DeleteMenuItemRequest, opts ...grpc.CallOption) (*DeleteMenuItemResponse, error)
	CreateModifierGroup(ctx context.Context, in *CreateModifierGroupRequest, opts ...grpc.CallOption) (*ModifierGroup, error)
	UpdateModifierGroup(ctx context.Context, in *UpdateModifierGroupRequest, opts ...grpc.CallOption) (*ModifierGroup, error)
	DeleteModifierGroup(ctx context.Context, in *DeleteModifierGroupRequest, opts ...grpc.CallOption) (*DeleteModifierGroupResponse, error)
}

type catalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogServiceClient(cc grpc.ClientConnInterface) CatalogServiceClient {
	return &catalogServiceClient{cc}
}

func (c *catalogServiceClient) GetMenu(ctx context.Context, in *GetMenuRequest, opts ...grpc.CallOption) (*GetMenuResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMenuResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetMenu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) ResolveOrderItems(ctx context.Context, in *ResolveOrderItemsRequest, opts ...grpc.CallOption) (*ResolveOrderItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveOrderItemsResponse)
	err := c.cc.Invoke(ctx, CatalogService_ResolveOrderItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) ResolveTable(ctx context.Context, in *ResolveTableRequest, opts ...grpc.CallOption) (*ResolveTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveTableResponse)
	err := c.cc.Invoke(ctx, CatalogService_ResolveTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) SetItemAvailability(ctx context.Context, in *SetItemAvailabilityRequest, opts ...grpc.CallOption) (*SetItemAvailabilityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetItemAvailabilityResponse)
	err := c.cc.Invoke(ctx, CatalogService_SetItemAvailability_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) GetVenueSettings(ctx context.Context, in *GetVenueSettingsRequest, opts ...grpc.CallOption) (*VenueSettings, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VenueSettings)
	err := c.cc.Invoke(ctx, CatalogService_GetVenueSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) UpdateVenueSettings(ctx context.Context, in *UpdateVenueSettingsRequest, opts ...grpc.CallOption) (*VenueSettings, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VenueSettings)
	err := c.cc.Invoke(ctx, CatalogService_UpdateVenueSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) ListHalls(ctx context.Context, in *ListHallsRequest, opts ...grpc.CallOption) (*ListHallsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHallsResponse)
	err := c.cc.Invoke(ctx, CatalogService_ListHalls_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) CreateHall(ctx context.Context, in *CreateHallRequest, opts ...grpc.CallOption) (*Hall, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Hall)
	err := c.cc.Invoke(ctx, CatalogService_CreateHall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) UpdateHall(ctx context.Context, in *UpdateHallRequest, opts ...grpc.CallOption) (*Hall, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Hall)
	err := c.cc.Invoke(ctx, CatalogService_UpdateHall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) DeleteHall(ctx context.Context, in *DeleteHallRequest, opts ...grpc.CallOption) (*DeleteHallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteHallResponse)
	err := c.cc.Invoke(ctx, CatalogService_DeleteHall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) ListTables(ctx context.Context, in *ListTablesRequest, opts ...grpc.CallOption) (*ListTablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTablesResponse)
	err := c.cc.Invoke(ctx, CatalogService_ListTables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) CreateTable(ctx context.Context, in *CreateTableRequest, opts ...grpc.CallOption) (*Table, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Table)
	err := c.cc.Invoke(ctx, CatalogService_CreateTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) UpdateTable(ctx context.Context, in *UpdateTableRequest, opts ...grpc.CallOption) (*Table, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Table)
	err := c.cc.Invoke(ctx, CatalogService_UpdateTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) DeleteTable(ctx context.Context, in *DeleteTableRequest, opts ...grpc.CallOption) (*DeleteTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTableResponse)
	err := c.cc.Invoke(ctx, CatalogService_DeleteTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) RotateVenueQRKey(ctx context.Context, in *RotateVenueQRKeyRequest, opts ...grpc.CallOption) (*RotateVenueQRKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateVenueQRKeyResponse)
	err := c.cc.Invoke(ctx, CatalogService_RotateVenueQRKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...grpc.CallOption) (*ListCategoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCategoriesResponse)
	err := c.cc.Invoke(ctx, CatalogService_ListCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*Category, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Category)
	err := c.cc.Invoke(ctx, CatalogService_CreateCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) UpdateCategory(ctx context.Context, in *UpdateCategoryRequest, opts ...grpc.CallOption) (*Category, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Category)
	err := c.cc.Invoke(ctx, CatalogService_UpdateCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*DeleteCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCategoryResponse)
	err := c.cc.Invoke(ctx, CatalogService_DeleteCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) ListMenuItems(ctx context.Context, in *ListMenuItemsRequest, opts ...grpc.CallOption) (*ListMenuItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMenuItemsResponse)
	err := c.cc.Invoke(ctx, CatalogService_ListMenuItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) CreateMenuItem(ctx context.Context, in *CreateMenuItemRequest, opts ...grpc.CallOption) (*MenuItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuItem)
	err := c.cc.Invoke(ctx, CatalogService_CreateMenuItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) UpdateMenuItem(ctx context.Context, in *UpdateMenuItemRequest, opts ...grpc.CallOption) (*MenuItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuItem)
	err := c.cc.Invoke(ctx, CatalogService_UpdateMenuItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) DeleteMenuItem(ctx context.Context, in *DeleteMenuItemRequest, opts ...grpc.CallOption) (*DeleteMenuItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMenuItemResponse)
	err := c.cc.Invoke(ctx, CatalogService_DeleteMenuItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) CreateModifierGroup(ctx context.Context, in *CreateModifierGroupRequest, opts ...grpc.CallOption) (*ModifierGroup, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModifierGroup)
	err := c.cc.Invoke(ctx, CatalogService_CreateModifierGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) UpdateModifierGroup(ctx context.Context, in *UpdateModifierGroupRequest, opts ...grpc.CallOption) (*ModifierGroup, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModifierGroup)
	err := c.cc.Invoke(ctx, CatalogService_UpdateModifierGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) DeleteModifierGroup(ctx context.Context, in *DeleteModifierGroupRequest, opts ...grpc.CallOption) (*DeleteModifierGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteModifierGroupResponse)
	err := c.cc.Invoke(ctx, CatalogService_DeleteModifierGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogServiceServer is the server API for CatalogService service.
// All implementations must embed UnimplementedCatalogServiceServer
// for forward compatibility.
type CatalogServiceServer interface {
	// GetMenu returns the full active, visible, in-locale menu for one venue
	// in a single response. Cacheable by menu_version (docs/TZ.md FR-C5, FR-C6).
	GetMenu(context.Context, *GetMenuRequest) (*GetMenuResponse, error)
	// ResolveOrderItems re-prices and validates availability of requested items
	// server-side; the client-displayed cart is never trusted (docs/TZ.md FR-O3).
	ResolveOrderItems(context.Context, *ResolveOrderItemsRequest) (*ResolveOrderItemsResponse, error)
	// ResolveTable validates a QR table_code + HMAC signature and returns the
	// venue/table it maps to (docs/TZ.md FR-T2, FR-T4).
	ResolveTable(context.Context, *ResolveTableRequest) (*ResolveTableResponse, error)
	// SetItemAvailability toggles the stop-list ("86") state of a menu item.
	SetItemAvailability(context.Context, *SetItemAvailabilityRequest) (*SetItemAvailabilityResponse, error)
	GetVenueSettings(context.Context, *GetVenueSettingsRequest) (*VenueSettings, error)
	UpdateVenueSettings(context.Context, *UpdateVenueSettingsRequest) (*VenueSettings, error)
	ListHalls(context.Context, *ListHallsRequest) (*ListHallsResponse, error)
	CreateHall(context.Context, *CreateHallRequest) (*Hall, error)
	UpdateHall(context.Context, *UpdateHallRequest) (*Hall, error)
	DeleteHall(context.Context, *DeleteHallRequest) (*DeleteHallResponse, error)
	ListTables(context.Context, *ListTablesRequest) (*ListTablesResponse, error)
	CreateTable(context.Context, *CreateTableRequest) (*Table, error)
	UpdateTable(context.Context, *UpdateTableRequest) (*Table, error)
	DeleteTable(context.Context, *DeleteTableRequest) (*DeleteTableResponse, error)
	// RotateVenueQRKey issues a new HMAC key_version for QR signing; the
	// previous version stays valid for the venue's configured grace period
	// (docs/TZ.md FR-T4).
	RotateVenueQRKey(context.Context, *RotateVenueQRKeyRequest) (*RotateVenueQRKeyResponse, error)
	ListCategories(context.Context, *ListCategoriesRequest) (*ListCategoriesResponse, error)
	CreateCategory(context.Context, *CreateCategoryRequest) (*Category, error)
	UpdateCategory(context.Context, *UpdateCategoryRequest) (*Category, error)
	DeleteCategory(context.Context, *DeleteCategoryRequest) (*DeleteCategoryResponse, error)
	ListMenuItems(context.Context, *ListMenuItemsRequest) (*ListMenuItemsResponse, error)
	CreateMenuItem(context.Context, *CreateMenuItemRequest) (*MenuItem, error)
	UpdateMenuItem(context.Context, *UpdateMenuItemRequest) (*MenuItem, error)
	DeleteMenuItem(context.Context, *DeleteMenuItemRequest) (*DeleteMenuItemResponse, error)
	CreateModifierGroup(context.Context, *CreateModifierGroupRequest) (*ModifierGroup, error)
	UpdateModifierGroup(context.Context, *UpdateModifierGroupRequest) (*ModifierGroup, error)
	DeleteModifierGroup(context.Context, *DeleteModifierGroupRequest) (*DeleteModifierGroupResponse, error)
	mustEmbedUnimplementedCatalogServiceServer()
}

// UnimplementedCatalogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogServiceServer struct{}

func (UnimplementedCatalogServiceServer) GetMenu(context.Context, *GetMenuRequest) (*GetMenuResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMenu not implemented")
}
func (UnimplementedCatalogServiceServer) ResolveOrderItems(context.Context, *ResolveOrderItemsRequest) (*ResolveOrderItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveOrderItems not implemented")
}
func (UnimplementedCatalogServiceServer) ResolveTable(context.Context, *ResolveTableRequest) (*ResolveTableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveTable not implemented")
}
func (UnimplementedCatalogServiceServer) SetItemAvailability(context.Context, *SetItemAvailabilityRequest) (*SetItemAvailabilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetItemAvailability not implemented")
}
func (UnimplementedCatalogServiceServer) GetVenueSettings(context.Context, *GetVenueSettingsRequest) (*VenueSettings, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVenueSettings not implemented")
}
func (UnimplementedCatalogServiceServer) UpdateVenueSettings(context.Context, *UpdateVenueSettingsRequest) (*VenueSettings, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateVenueSettings not implemented")
}
func (UnimplementedCatalogServiceServer) ListHalls(context.Context, *ListHallsRequest) (*ListHallsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHalls not implemented")
}
func (UnimplementedCatalogServiceServer) CreateHall(context.Context, *CreateHallRequest) (*Hall, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHall not implemented")
}
func (UnimplementedCatalogServiceServer) UpdateHall(context.Context, *UpdateHallRequest) (*Hall, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateHall not implemented")
}
func (UnimplementedCatalogServiceServer) DeleteHall(context.Context, *DeleteHallRequest) (*DeleteHallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteHall not implemented")
}
func (UnimplementedCatalogServiceServer) ListTables(context.Context, *ListTablesRequest) (*ListTablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTables not implemented")
}
func (UnimplementedCatalogServiceServer) CreateTable(context.Context, *CreateTableRequest) (*Table, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTable not implemented")
}
func (UnimplementedCatalogServiceServer) UpdateTable(context.Context, *UpdateTableRequest) (*Table, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTable not implemented")
}
func (UnimplementedCatalogServiceServer) DeleteTable(context.Context, *DeleteTableRequest) (*DeleteTableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTable not implemented")
}
func (UnimplementedCatalogServiceServer) RotateVenueQRKey(context.Context, *RotateVenueQRKeyRequest) (*RotateVenueQRKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RotateVenueQRKey not implemented")
}
func (UnimplementedCatalogServiceServer) ListCategories(context.Context, *ListCategoriesRequest) (*ListCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCategories not implemented")
}
func (UnimplementedCatalogServiceServer) CreateCategory(context.Context, *CreateCategoryRequest) (*Category, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCategory not implemented")
}
func (UnimplementedCatalogServiceServer) UpdateCategory(context.Context, *UpdateCategoryRequest) (*Category, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCategory not implemented")
}
func (UnimplementedCatalogServiceServer) DeleteCategory(context.Context, *DeleteCategoryRequest) (*DeleteCategoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCategory not implemented")
}
func (UnimplementedCatalogServiceServer) ListMenuItems(context.Context, *ListMenuItemsRequest) (*ListMenuItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMenuItems not implemented")
}
func (UnimplementedCatalogServiceServer) CreateMenuItem(context.Context, *CreateMenuItemRequest) (*MenuItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMenuItem not implemented")
}
func (UnimplementedCatalogServiceServer) UpdateMenuItem(context.Context, *UpdateMenuItemRequest) (*MenuItem, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMenuItem not implemented")
}
func (UnimplementedCatalogServiceServer) DeleteMenuItem(context.Context, *DeleteMenuItemRequest) (*DeleteMenuItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMenuItem not implemented")
}
func (UnimplementedCatalogServiceServer) CreateModifierGroup(context.Context, *CreateModifierGroupRequest) (*ModifierGroup, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateModifierGroup not implemented")
}
func (UnimplementedCatalogServiceServer) UpdateModifierGroup(context.Context, *UpdateModifierGroupRequest) (*ModifierGroup, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateModifierGroup not implemented")
}
func (UnimplementedCatalogServiceServer) DeleteModifierGroup(context.Context, *DeleteModifierGroupRequest) (*DeleteModifierGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteModifierGroup not implemented")
}
func (UnimplementedCatalogServiceServer) mustEmbedUnimplementedCatalogServiceServer() {}
func (UnimplementedCatalogServiceServer) testEmbeddedByValue()                        {}

// UnsafeCatalogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogServiceServer will
// result in compilation errors.
type UnsafeCatalogServiceServer interface {
	mustEmbedUnimplementedCatalogServiceServer()
}

func RegisterCatalogServiceServer(s grpc.ServiceRegistrar, srv CatalogServiceServer) {
	// If the following call pancis, it indicates UnimplementedCatalogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatalogService_ServiceDesc, srv)
}

func _CatalogService_GetMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMenuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetMenu(ctx, req.(*GetMenuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_ResolveOrderItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveOrderItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ResolveOrderItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_ResolveOrderItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ResolveOrderItems(ctx, req.(*ResolveOrderItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_ResolveTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ResolveTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_ResolveTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ResolveTable(ctx, req.(*ResolveTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_SetItemAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetItemAvailabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).SetItemAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_SetItemAvailability_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).SetItemAvailability(ctx, req.(*SetItemAvailabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_GetVenueSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVenueSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetVenueSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetVenueSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetVenueSettings(ctx, req.(*GetVenueSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_UpdateVenueSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVenueSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).UpdateVenueSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_UpdateVenueSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).UpdateVenueSettings(ctx, req.(*UpdateVenueSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_ListHalls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHallsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ListHalls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_ListHalls_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ListHalls(ctx, req.(*ListHallsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_CreateHall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).CreateHall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_CreateHall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).CreateHall(ctx, req.(*CreateHallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_UpdateHall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).UpdateHall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_UpdateHall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).UpdateHall(ctx, req.(*UpdateHallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_DeleteHall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).DeleteHall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_DeleteHall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).DeleteHall(ctx, req.(*DeleteHallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_ListTables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ListTables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_ListTables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ListTables(ctx, req.(*ListTablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_CreateTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).CreateTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_CreateTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).CreateTable(ctx, req.(*CreateTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_UpdateTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).UpdateTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_UpdateTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).UpdateTable(ctx, req.(*UpdateTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_DeleteTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).DeleteTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_DeleteTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).DeleteTable(ctx, req.(*DeleteTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_RotateVenueQRKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateVenueQRKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).RotateVenueQRKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_RotateVenueQRKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).RotateVenueQRKey(ctx, req.(*RotateVenueQRKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_ListCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ListCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_ListCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ListCategories(ctx, req.(*ListCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_CreateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).CreateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_CreateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).CreateCategory(ctx, req.(*CreateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_UpdateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).UpdateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_UpdateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).UpdateCategory(ctx, req.(*UpdateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_DeleteCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).DeleteCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_DeleteCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).DeleteCategory(ctx, req.(*DeleteCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_ListMenuItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMenuItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ListMenuItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_ListMenuItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ListMenuItems(ctx, req.(*ListMenuItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_CreateMenuItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMenuItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).CreateMenuItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_CreateMenuItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).CreateMenuItem(ctx, req.(*CreateMenuItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_UpdateMenuItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMenuItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).UpdateMenuItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_UpdateMenuItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).UpdateMenuItem(ctx, req.(*UpdateMenuItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_DeleteMenuItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMenuItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).DeleteMenuItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_DeleteMenuItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).DeleteMenuItem(ctx, req.(*DeleteMenuItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_CreateModifierGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateModifierGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).CreateModifierGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_CreateModifierGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).CreateModifierGroup(ctx, req.(*CreateModifierGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_UpdateModifierGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateModifierGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).UpdateModifierGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_UpdateModifierGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).UpdateModifierGroup(ctx, req.(*UpdateModifierGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_DeleteModifierGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteModifierGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).DeleteModifierGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_DeleteModifierGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).DeleteModifierGroup(ctx, req.(*DeleteModifierGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogService_ServiceDesc is the grpc.ServiceDesc for CatalogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "catalog.v1.CatalogService",
	HandlerType: (*CatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMenu",
			Handler:    _CatalogService_GetMenu_Handler,
		},
		{
			MethodName: "ResolveOrderItems",
			Handler:    _CatalogService_ResolveOrderItems_Handler,
		},
		{
			MethodName: "ResolveTable",
			Handler:    _CatalogService_ResolveTable_Handler,
		},
		{
			MethodName: "SetItemAvailability",
			Handler:    _CatalogService_SetItemAvailability_Handler,
		},
		{
			MethodName: "GetVenueSettings",
			Handler:    _CatalogService_GetVenueSettings_Handler,
		},
		{
			MethodName: "UpdateVenueSettings",
			Handler:    _CatalogService_UpdateVenueSettings_Handler,
		},
		{
			MethodName: "ListHalls",
			Handler:    _CatalogService_ListHalls_Handler,
		},
		{
			MethodName: "CreateHall",
			Handler:    _CatalogService_CreateHall_Handler,
		},
		{
			MethodName: "UpdateHall",
			Handler:    _CatalogService_UpdateHall_Handler,
		},
		{
			MethodName: "DeleteHall",
			Handler:    _CatalogService_DeleteHall_Handler,
		},
		{
			MethodName: "ListTables",
			Handler:    _CatalogService_ListTables_Handler,
		},
		{
			MethodName: "CreateTable",
			Handler:    _CatalogService_CreateTable_Handler,
		},
		{
			MethodName: "UpdateTable",
			Handler:    _CatalogService_UpdateTable_Handler,
		},
		{
			MethodName: "DeleteTable",
			Handler:    _CatalogService_DeleteTable_Handler,
		},
		{
			MethodName: "RotateVenueQRKey",
			Handler:    _CatalogService_RotateVenueQRKey_Handler,
		},
		{
			MethodName: "ListCategories",
			Handler:    _CatalogService_ListCategories_Handler,
		},
		{
			MethodName: "CreateCategory",
			Handler:    _CatalogService_CreateCategory_Handler,
		},
		{
			MethodName: "UpdateCategory",
			Handler:    _CatalogService_UpdateCategory_Handler,
		},
		{
			MethodName: "DeleteCategory",
			Handler:    _CatalogService_DeleteCategory_Handler,
		},
		{
			MethodName: "ListMenuItems",
			Handler:    _CatalogService_ListMenuItems_Handler,
		},
		{
			MethodName: "CreateMenuItem",
			Handler:    _CatalogService_CreateMenuItem_Handler,
		},
		{
			MethodName: "UpdateMenuItem",
			Handler:    _CatalogService_UpdateMenuItem_Handler,
		},
		{
			MethodName: "DeleteMenuItem",
			Handler:    _CatalogService_DeleteMenuItem_Handler,
		},
		{
			MethodName: "CreateModifierGroup",
			Handler:    _CatalogService_CreateModifierGroup_Handler,
		},
		{
			MethodName: "UpdateModifierGroup",
			Handler:    _CatalogService_UpdateModifierGroup_Handler,
		},
		{
			MethodName: "DeleteModifierGroup",
			Handler:    _CatalogService_DeleteModifierGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "catalog.proto",
}
