// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	admin "github.com/menli02/QR-menu/services/gateway/internal/handler/admin"
	auth "github.com/menli02/QR-menu/services/gateway/internal/handler/auth"
	floor "github.com/menli02/QR-menu/services/gateway/internal/handler/floor"
	guest "github.com/menli02/QR-menu/services/gateway/internal/handler/guest"
	kds "github.com/menli02/QR-menu/services/gateway/internal/handler/kds"
	"github.com/menli02/QR-menu/services/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.StaffAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/categories",
					Handler: admin.ListCategoriesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/categories",
					Handler: admin.CreateCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/categories/:id",
					Handler: admin.UpdateCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/categories/:id",
					Handler: admin.DeleteCategoryHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/halls",
					Handler: admin.ListHallsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/halls",
					Handler: admin.CreateHallHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/halls/:id",
					Handler: admin.UpdateHallHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/halls/:id",
					Handler: admin.DeleteHallHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/items",
					Handler: admin.ListMenuItemsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/items",
					Handler: admin.CreateMenuItemHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/items/:id",
					Handler: admin.UpdateMenuItemHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/items/:id",
					Handler: admin.DeleteMenuItemHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/items/:itemId/modifier-groups",
					Handler: admin.CreateModifierGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/items/:itemId/modifier-groups/:groupId",
					Handler: admin.UpdateModifierGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/items/:itemId/modifier-groups/:groupId",
					Handler: admin.DeleteModifierGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/reports/day",
					Handler: admin.GetDayReportHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/staff",
					Handler: admin.ListStaffHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/staff",
					Handler: admin.CreateStaffHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/staff/:id",
					Handler: admin.UpdateStaffHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/staff/:id",
					Handler: admin.DeleteStaffHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/tables",
					Handler: admin.ListTablesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/tables",
					Handler: admin.CreateTableHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/tables/:id",
					Handler: admin.UpdateTableHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/tables/:id",
					Handler: admin.DeleteTableHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/tables/rotate-qr-key",
					Handler: admin.RotateVenueQrKeyHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/venue",
					Handler: admin.GetVenueSettingsHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/venue",
					Handler: admin.UpdateVenueSettingsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/logout",
				Handler: auth.LogoutHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/refresh",
				Handler: auth.RefreshHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.StaffAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/service-requests",
					Handler: floor.ListServiceRequestsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/service-requests/:id/transition",
					Handler: floor.TransitionServiceRequestHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/table-sessions/:id/bill",
					Handler: floor.GetTableSessionBillHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/table-sessions/:id/close",
					Handler: floor.CloseTableSessionHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/tables",
					Handler: floor.ListFloorTablesHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/floor"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/sessions",
				Handler: guest.ExchangeGuestSessionHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/guest"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.GuestAuth},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/bill",
					Handler: guest.GetGuestBillHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/menu",
					Handler: guest.GetGuestMenuHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/orders",
					Handler: guest.CreateGuestOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/orders",
					Handler: guest.ListGuestOrdersHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/orders/:id/cancel",
					Handler: guest.CancelGuestOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/service-requests",
					Handler: guest.CreateGuestServiceRequestHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/guest"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.StaffAuth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/items/:itemId/availability",
					Handler: kds.SetItemAvailabilityHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/order-items/:id/transition",
					Handler: kds.TransitionOrderItemHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/orders/:id/transition",
					Handler: kds.TransitionOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/tickets",
					Handler: kds.ListTicketsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/kds"),
	)
}
