// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: order.proto

package orderservice

import (
	"context"

	"github.com/menli02/QR-menu/proto/order/v1"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Bill                            = v1_orderpb.Bill
	CloseTableSessionRequest        = v1_orderpb.CloseTableSessionRequest
	CreateOrderRequest              = v1_orderpb.CreateOrderRequest
	CreateServiceRequestRequest     = v1_orderpb.CreateServiceRequestRequest
	DayReport                       = v1_orderpb.DayReport
	GetBillRequest                  = v1_orderpb.GetBillRequest
	GetDayReportRequest             = v1_orderpb.GetDayReportRequest
	GetTableSessionRequest          = v1_orderpb.GetTableSessionRequest
	ListActiveTableSessionsRequest  = v1_orderpb.ListActiveTableSessionsRequest
	ListActiveTableSessionsResponse = v1_orderpb.ListActiveTableSessionsResponse
	ListOrdersRequest               = v1_orderpb.ListOrdersRequest
	ListOrdersResponse              = v1_orderpb.ListOrdersResponse
	ListServiceRequestsRequest      = v1_orderpb.ListServiceRequestsRequest
	ListServiceRequestsResponse     = v1_orderpb.ListServiceRequestsResponse
	ListTicketsRequest              = v1_orderpb.ListTicketsRequest
	ListTicketsResponse             = v1_orderpb.ListTicketsResponse
	Order                           = v1_orderpb.Order
	ServiceRequest                  = v1_orderpb.ServiceRequest
	TableSession                    = v1_orderpb.TableSession
	TransitionOrderItemRequest      = v1_orderpb.TransitionOrderItemRequest
	TransitionOrderRequest          = v1_orderpb.TransitionOrderRequest
	TransitionServiceRequestRequest = v1_orderpb.TransitionServiceRequestRequest

	OrderService interface {
		// CreateOrder is idempotent on idempotency_key (scoped to venue_id).
		CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*Order, error)
		ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (*ListOrdersResponse, error)
		GetBill(ctx context.Context, in *GetBillRequest, opts ...grpc.CallOption) (*Bill, error)
		CreateServiceRequest(ctx context.Context, in *CreateServiceRequestRequest, opts ...grpc.CallOption) (*ServiceRequest, error)
		TransitionOrder(ctx context.Context, in *TransitionOrderRequest, opts ...grpc.CallOption) (*Order, error)
		TransitionOrderItem(ctx context.Context, in *TransitionOrderItemRequest, opts ...grpc.CallOption) (*Order, error)
		ListTickets(ctx context.Context, in *ListTicketsRequest, opts ...grpc.CallOption) (*ListTicketsResponse, error)
		GetTableSession(ctx context.Context, in *GetTableSessionRequest, opts ...grpc.CallOption) (*TableSession, error)
		ListActiveTableSessions(ctx context.Context, in *ListActiveTableSessionsRequest, opts ...grpc.CallOption) (*ListActiveTableSessionsResponse, error)
		CloseTableSession(ctx context.Context, in *CloseTableSessionRequest, opts ...grpc.CallOption) (*TableSession, error)
		ListServiceRequests(ctx context.Context, in *ListServiceRequestsRequest, opts ...grpc.CallOption) (*ListServiceRequestsResponse, error)
		TransitionServiceRequest(ctx context.Context, in *TransitionServiceRequestRequest, opts ...grpc.CallOption) (*ServiceRequest, error)
		GetDayReport(ctx context.Context, in *GetDayReportRequest, opts ...grpc.CallOption) (*DayReport, error)
	}

	defaultOrderService struct {
		cli zrpc.Client
	}
)

func NewOrderService(cli zrpc.Client) OrderService {
	return &defaultOrderService{
		cli: cli,
	}
}

// CreateOrder is idempotent on idempotency_key (scoped to venue_id).
func (m *defaultOrderService) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*Order, error) {
	client := v1_orderpb.NewOrderServiceClient(m.cli.Conn())
	return client.CreateOrder(ctx, in, opts...)
}

func (m *defaultOrderService) ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (*ListOrdersResponse, error) {
	client := v1_orderpb.NewOrderServiceClient(m.cli.Conn())
	return client.ListOrders(ctx, in, opts...)
}

func (m *defaultOrderService) GetBill(ctx context.Context, in *GetBillRequest, opts ...grpc.CallOption) (*Bill, error) {
	client := v1_orderpb.NewOrderServiceClient(m.cli.Conn())
	return client.GetBill(ctx, in, opts...)
}

func (m *defaultOrderService) CreateServiceRequest(ctx context.Context, in *CreateServiceRequestRequest, opts ...grpc.CallOption) (*ServiceRequest, error) {
	client := v1_orderpb.NewOrderServiceClient(m.cli.Conn())
	return client.CreateServiceRequest(ctx, in, opts...)
}

func (m *defaultOrderService) TransitionOrder(ctx context.Context, in *TransitionOrderRequest, opts ...grpc.CallOption) (*Order, error) {
	client := v1_orderpb.NewOrderServiceClient(m.cli.Conn())
	return client.TransitionOrder(ctx, in, opts...)
}

func (m *defaultOrderService) TransitionOrderItem(ctx context.Context, in *TransitionOrderItemRequest, opts ...grpc.CallOption) (*Order, error) {
	client := v1_orderpb.NewOrderServiceClient(m.cli.Conn())
	return client.TransitionOrderItem(ctx, in, opts...)
}

func (m *defaultOrderService) ListTickets(ctx context.Context, in *ListTicketsRequest, opts ...grpc.CallOption) (*ListTicketsResponse, error) {
	client := v1_orderpb.NewOrderServiceClient(m.cli.Conn())
	return client.ListTickets(ctx, in, opts...)
}

func (m *defaultOrderService) GetTableSession(ctx context.Context, in *GetTableSessionRequest, opts ...grpc.CallOption) (*TableSession, error) {
	client := v1_orderpb.NewOrderServiceClient(m.cli.Conn())
	return client.GetTableSession(ctx, in, opts...)
}

func (m *defaultOrderService) ListActiveTableSessions(ctx context.Context, in *ListActiveTableSessionsRequest, opts ...grpc.CallOption) (*ListActiveTableSessionsResponse, error) {
	client := v1_orderpb.NewOrderServiceClient(m.cli.Conn())
	return client.ListActiveTableSessions(ctx, in, opts...)
}

func (m *defaultOrderService) CloseTableSession(ctx context.Context, in *CloseTableSessionRequest, opts ...grpc.CallOption) (*TableSession, error) {
	client := v1_orderpb.NewOrderServiceClient(m.cli.Conn())
	return client.CloseTableSession(ctx, in, opts...)
}

func (m *defaultOrderService) ListServiceRequests(ctx context.Context, in *ListServiceRequestsRequest, opts ...grpc.CallOption) (*ListServiceRequestsResponse, error) {
	client := v1_orderpb.NewOrderServiceClient(m.cli.Conn())
	return client.ListServiceRequests(ctx, in, opts...)
}

func (m *defaultOrderService) TransitionServiceRequest(ctx context.Context, in *TransitionServiceRequestRequest, opts ...grpc.CallOption) (*ServiceRequest, error) {
	client := v1_orderpb.NewOrderServiceClient(m.cli.Conn())
	return client.TransitionServiceRequest(ctx, in, opts...)
}

func (m *defaultOrderService) GetDayReport(ctx context.Context, in *GetDayReportRequest, opts ...grpc.CallOption) (*DayReport, error) {
	client := v1_orderpb.NewOrderServiceClient(m.cli.Conn())
	return client.GetDayReport(ctx, in, opts...)
}
