// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: identity.proto

package server

import (
	"context"

	"github.com/menli02/QR-menu/proto/identity/v1"
	"github.com/menli02/QR-menu/services/identity/internal/logic/identityservice"
	"github.com/menli02/QR-menu/services/identity/internal/svc"
)

type IdentityServiceServer struct {
	svcCtx *svc.ServiceContext
	v1_identitypb.UnimplementedIdentityServiceServer
}

func NewIdentityServiceServer(svcCtx *svc.ServiceContext) *IdentityServiceServer {
	return &IdentityServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *IdentityServiceServer) Login(ctx context.Context, in *v1_identitypb.LoginRequest) (*v1_identitypb.TokenPair, error) {
	l := identityservicelogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *IdentityServiceServer) Refresh(ctx context.Context, in *v1_identitypb.RefreshRequest) (*v1_identitypb.TokenPair, error) {
	l := identityservicelogic.NewRefreshLogic(ctx, s.svcCtx)
	return l.Refresh(in)
}

func (s *IdentityServiceServer) Revoke(ctx context.Context, in *v1_identitypb.RevokeRequest) (*v1_identitypb.RevokeResponse, error) {
	l := identityservicelogic.NewRevokeLogic(ctx, s.svcCtx)
	return l.Revoke(in)
}

func (s *IdentityServiceServer) GetStaff(ctx context.Context, in *v1_identitypb.GetStaffRequest) (*v1_identitypb.Staff, error) {
	l := identityservicelogic.NewGetStaffLogic(ctx, s.svcCtx)
	return l.GetStaff(in)
}

// IssueGuestToken mints an anonymous guest JWT bound to
func (s *IdentityServiceServer) IssueGuestToken(ctx context.Context, in *v1_identitypb.IssueGuestTokenRequest) (*v1_identitypb.TokenPair, error) {
	l := identityservicelogic.NewIssueGuestTokenLogic(ctx, s.svcCtx)
	return l.IssueGuestToken(in)
}

// ListJWKS exposes the public signing keys so gateway instances can
func (s *IdentityServiceServer) ListJWKS(ctx context.Context, in *v1_identitypb.ListJWKSRequest) (*v1_identitypb.JWKS, error) {
	l := identityservicelogic.NewListJWKSLogic(ctx, s.svcCtx)
	return l.ListJWKS(in)
}

func (s *IdentityServiceServer) ListStaff(ctx context.Context, in *v1_identitypb.ListStaffRequest) (*v1_identitypb.ListStaffResponse, error) {
	l := identityservicelogic.NewListStaffLogic(ctx, s.svcCtx)
	return l.ListStaff(in)
}

func (s *IdentityServiceServer) CreateStaff(ctx context.Context, in *v1_identitypb.CreateStaffRequest) (*v1_identitypb.Staff, error) {
	l := identityservicelogic.NewCreateStaffLogic(ctx, s.svcCtx)
	return l.CreateStaff(in)
}

func (s *IdentityServiceServer) UpdateStaff(ctx context.Context, in *v1_identitypb.UpdateStaffRequest) (*v1_identitypb.Staff, error) {
	l := identityservicelogic.NewUpdateStaffLogic(ctx, s.svcCtx)
	return l.UpdateStaff(in)
}

func (s *IdentityServiceServer) DeleteStaff(ctx context.Context, in *v1_identitypb.DeleteStaffRequest) (*v1_identitypb.DeleteStaffResponse, error) {
	l := identityservicelogic.NewDeleteStaffLogic(ctx, s.svcCtx)
	return l.DeleteStaff(in)
}

func (s *IdentityServiceServer) SetStaffPassword(ctx context.Context, in *v1_identitypb.SetStaffPasswordRequest) (*v1_identitypb.SetStaffPasswordResponse, error) {
	l := identityservicelogic.NewSetStaffPasswordLogic(ctx, s.svcCtx)
	return l.SetStaffPassword(in)
}
